### ISSUE TITLE
Misleading error message in preflight validation

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#1033]
**What happened**:

Adding a non eksa object with custom namespace in cluster spec file when creating a cluster will fail preflight validation with misleading error message:
"VsphereMachineConfig and Cluster objects must have the same namespace specified"

**What you expected to happen**:

Preflight validation should fail w error message like "Unsupported Object Kind: xyzKind"

**How to reproduce it (as minimally and precisely as possible)**:

Take a valid eksa cluster spec, and add the following object to the top:

```yaml
apiVersion: x.y.z.com/v1alpha1
kind: NonEKSAKind
metadata:
  name: non-eksa-object
  namespace: custom-system
spec:
  x: y
```
then create a cluster with that file. 

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:
