### ISSUE TITLE
"Moving cluster management from bootstrap to workload cluster" step fails in 0.7.0 using Bottlerocket OS

### ISSUE THREAD

**Issue by itaytalmi** [aws/eks-anywhere#1156]
**What happened**:

In the same environment I mentioned in #1155, the `Moving cluster management from bootstrap to workload cluster` step fails in 0.7.0 with the following message:

```text
$ eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml

Performing setup and validations
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
Creating template. This might take a while.
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Control plane and Workload templates validated
✅ Vsphere Provider setup is valid
✅ Create preflight validations pass
Creating new bootstrap cluster
Installing cluster-api providers on bootstrap cluster
Provider specific setup
Creating new workload cluster
Installing networking on workload cluster
Installing storage class on workload cluster
Installing cluster-api providers on workload cluster
Installing EKS-A secrets on workload cluster
Moving cluster management from bootstrap to workload cluster
collecting cluster diagnostics
collecting management cluster diagnostics
⏳ Collecting support bundle from cluster, this can take a while        {"cluster": "bootstrap-cluster", "bundle": "it-eksa-mgmt/generated/bootstrap-cluster-2022-02-05T13:58:28Z-bundle.yaml", "since": 1644065908000245091, "kubeconfig": "it-eksa-mgmt/generated/it-eksa-mgmt.kind.kubeconfig"}
Support bundle archive created  {"path": "support-bundle-2022-02-05T13_58_29.tar.gz"}
Analyzing support bundle        {"bundle": "it-eksa-mgmt/generated/bootstrap-cluster-2022-02-05T13:58:28Z-bundle.yaml", "archive": "support-bundle-2022-02-05T13_58_29.tar.gz"}
Analysis output generated       {"path": "it-eksa-mgmt/generated/bootstrap-cluster-2022-02-05T14:00:16Z-analysis.yaml"}
collecting workload cluster diagnostics
⏳ Collecting support bundle from cluster, this can take a while        {"cluster": "it-eksa-mgmt", "bundle": "it-eksa-mgmt/generated/it-eksa-mgmt-2022-02-05T14:00:23Z-bundle.yaml", "since": 1644066023917299387, "kubeconfig": "it-eksa-mgmt/it-eksa-mgmt-eks-a-cluster.kubeconfig"}
Support bundle archive created  {"path": "support-bundle-2022-02-05T14_00_24.tar.gz"}
Analyzing support bundle        {"bundle": "it-eksa-mgmt/generated/it-eksa-mgmt-2022-02-05T14:00:23Z-bundle.yaml", "archive": "support-bundle-2022-02-05T14_00_24.tar.gz"}
Analysis output generated       {"path": "it-eksa-mgmt/generated/it-eksa-mgmt-2022-02-05T14:03:04Z-analysis.yaml"}
Error: failed to create cluster: error moving CAPI management from source to target: failed moving management cluster: Performing move...
Discovering Cluster API objects
Moving Cluster API objects Clusters=1
Creating objects in the target cluster
Error: action failed after 10 attempts: error creating "controlplane.cluster.x-k8s.io/v1beta1, Kind=KubeadmControlPlane" eksa-system/it-eksa-mgmt: Internal error occurred: failed calling webhook "default.kubeadmcontrolplane.controlplane.cluster.x-k8s.io": Post "https://capi-kubeadm-control-plane-webhook-service.capi-kubeadm-control-plane-system.svc:443/mutate-controlplane-cluster-x-k8s-io-v1beta1-kubeadmcontrolplane?timeout=10s": context deadline exceeded
```

`kubectl get nodes` returns:

```text
$ kubectl get nodes

NAME             STATUS   ROLES                  AGE   VERSION
10.100.137.107   Ready    control-plane,master   17m   v1.21.6
10.100.137.108   Ready    <none>                 16m   v1.21.6
10.100.137.109   Ready    control-plane,master   15m   v1.21.6
10.100.137.55    Ready    <none>                 16m   v1.21.6
```

`kubectl get pods -A` returns:

```text
$ kubectl get pod -A

NAMESPACE                           NAME                                                             READY   STATUS    RESTARTS   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-694cc79bb7-7lz9s       1/1     Running   0          14m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-5b6b48dd8c-k6c8r   1/1     Running   0          14m
capi-system                         capi-controller-manager-689cd9b4fd-5vp2c                         1/1     Running   0          14m
capv-system                         capv-controller-manager-6b467446b9-x4d4z                         1/1     Running   0          14m
cert-manager                        cert-manager-7988d4fb6c-wwbfl                                    1/1     Running   0          16m
cert-manager                        cert-manager-cainjector-6bc8dcdb64-7xjst                         1/1     Running   0          16m
cert-manager                        cert-manager-webhook-68979bfb95-rsghj                            1/1     Running   0          16m
etcdadm-bootstrap-provider-system   etcdadm-bootstrap-provider-controller-manager-74c86ffb56-xzh9x   1/1     Running   0          14m
etcdadm-controller-system           etcdadm-controller-controller-manager-7894945688-rvcct           1/1     Running   0          14m
kube-system                         cilium-5nkz5                                                     1/1     Running   0          16m
kube-system                         cilium-5wdj4                                                     1/1     Running   0          16m
kube-system                         cilium-f8t7l                                                     1/1     Running   0          16m
kube-system                         cilium-mzz9q                                                     1/1     Running   0          16m
kube-system                         cilium-operator-86d59d5c88-mdspl                                 1/1     Running   0          16m
kube-system                         cilium-operator-86d59d5c88-vlcqn                                 1/1     Running   0          16m
kube-system                         coredns-745c7986c7-cdvzg                                         1/1     Running   0          18m
kube-system                         coredns-745c7986c7-kglxn                                         1/1     Running   0          18m
kube-system                         kube-apiserver-10.100.137.107                                    1/1     Running   0          18m
kube-system                         kube-apiserver-10.100.137.109                                    1/1     Running   0          16m
kube-system                         kube-controller-manager-10.100.137.107                           1/1     Running   0          18m
kube-system                         kube-controller-manager-10.100.137.109                           1/1     Running   0          16m
kube-system                         kube-proxy-58jwb                                                 1/1     Running   0          18m
kube-system                         kube-proxy-8t4gv                                                 1/1     Running   0          17m
kube-system                         kube-proxy-bgh5h                                                 1/1     Running   0          16m
kube-system                         kube-proxy-pl7g5                                                 1/1     Running   0          17m
kube-system                         kube-scheduler-10.100.137.107                                    1/1     Running   0          18m
kube-system                         kube-scheduler-10.100.137.109                                    1/1     Running   0          16m
kube-system                         kube-vip-10.100.137.107                                          1/1     Running   0          18m
kube-system                         kube-vip-10.100.137.109                                          1/1     Running   0          16m
kube-system                         vsphere-cloud-controller-manager-gplzh                           1/1     Running   2          16m
kube-system                         vsphere-cloud-controller-manager-lwbk2                           1/1     Running   2          18m
kube-system                         vsphere-cloud-controller-manager-tc9gs                           1/1     Running   2          17m
kube-system                         vsphere-cloud-controller-manager-w5g96                           1/1     Running   2          17m
kube-system                         vsphere-csi-controller-576c9c8dc8-b8jwr                          5/5     Running   0          18m
kube-system                         vsphere-csi-node-fpn8b                                           3/3     Running   0          17m
kube-system                         vsphere-csi-node-hlp2m                                           3/3     Running   0          16m
kube-system                         vsphere-csi-node-jhn8g                                           3/3     Running   0          17m
kube-system                         vsphere-csi-node-twh7m                                           3/3     Running   0          18m
```

In one of the attempts I didn't even get that far and the `Installing cluster-api providers on workload cluster` step was completely stuck.

In another attempt, the same `Moving cluster management from bootstrap to workload cluster` step failed as well, but only after terminating the `capi-kubeadm-bootstrap-controller-manager`, `capi-kubeadm-control-plane-controller-manager`, `etcdadm-bootstrap-provider-controller-manager`, and `etcdadm-controller-controller-manager` pods. This time, that didn't happen for some reason...
I cannot explain the different behaviors.

The cluster creation cannot complete due to the above errors.

**How to reproduce it (as minimally and precisely as possible)**:

Simply create a standard cluster.

My cluster spec:

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: it-eksa-mgmt
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "10.100.137.210"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: it-eksa-mgmt-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: it-eksa-mgmt
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: it-eksa-mgmt-etcd
  kubernetesVersion: "1.21"
  managementCluster:
    name: it-eksa-mgmt
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: it-eksa-mgmt
    name: md-0
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: it-eksa-mgmt
spec:
  datacenter: "my-datacenter"
  insecure: false
  network: "eksa-node-network-01"
  server: "my-vcenter.example.domain"
  thumbprint: "26:3A:FF:3E:01:84:36:F5:BC:18:80:27:0E:14:59:AB:8E:1B:9E:53"
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: it-eksa-mgmt-cp
spec:
  datastore: "vsanDatastore"
  diskGiB: 25
  folder: "/Demo-Datacenter/vm/LABS/K8S/EKSA"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/Demo-Datacenter/host/Demo-Cluster/Resources"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3Nz.....
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: it-eksa-mgmt
spec:
  datastore: "vsanDatastore"
  diskGiB: 25
  folder: "/Demo-Datacenter/vm/LABS/K8S/EKSA"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/Demo-Datacenter/host/Demo-Cluster/Resources"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3Nz.....
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: it-eksa-mgmt-etcd
spec:
  datastore: "vsanDatastore"
  diskGiB: 25
  folder: "/Demo-Datacenter/vm/LABS/K8S/EKSA"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/Demo-Datacenter/host/Demo-Cluster/Resources"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3Nz.....
```

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.7.0
- EKS distro version: v1-21-eks-8
- eksctl version: 0.82.0
- VMware vCenter Server version: 7.0.2.00100 (Update 3b, build number 18901211)
- Admin VM is Linux Ubuntu 20.04.3 LTS (Focal Fossa).
- Docker version: 20.10.12

The same spec works using the 0.6.1 binary.

I have uploaded both the bootstrap-cluster and the mgmt-cluster support bundles to my S3 bucket:

https://ts-k8s-pub.s3.eu-central-1.amazonaws.com/aws-eks-anywhere/logs/bootstrap-cluster-support-bundle-2022-02-05T13_58_29.tar.gz

https://ts-k8s-pub.s3.eu-central-1.amazonaws.com/aws-eks-anywhere/logs/mgmt-cluster-support-bundle-2022-02-05T14_00_24.tar.gz

P.S - something strange I've noticed is that `kubectl get nodes` displays Kubernetes version `v1.21.6` while the template name is `bottlerocket-v1.21.5-kubernetes-1-21-eks-8-amd64`.

Assistance will be appreciated.
