### ISSUE TITLE
[EKS-A 0.7.2] Cilium and Cilium Operator images cannot be pulled from the private image registry when using the registry mirror spec and the --bundles-override option in an air-gapped environment

### ISSUE THREAD

**Issue by itaytalmi** [aws/eks-anywhere#1373]
**What happened**:

I'm trying to deploy EKS-A in an air-gapped environment, using a private image registry and the `--bundles-override` option.
During the deployment of the management cluster, I can see that the Cilium and the Cilium Operator pods are unable to start because their image cannot be pulled from the private registry, and I think the nodes are actually trying to pull the wrong Cilium images...

Running `kubectl describe pod -l io.cilium/app=operator -n kube-system` and `kubectl describe pod -l k8s-app=cilium -n kube-system`, I can see that the nodes are trying to pull the `public.ecr.aws/isovalent/operator-generic:v1.9.10-eksa.1` and `public.ecr.aws/isovalent/cilium:v1.9.10-eksa.1` images:

```text
$ kubectl describe pod -l io.cilium/app=operator -n kube-system

...
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  Failed   17m (x10 over 87m)     kubelet  Failed to pull image "public.ecr.aws/isovalent/operator-generic:v1.9.10-eksa.1": rpc error: code = Unknown desc = failed to pull and unpack image "public.ecr.aws/isovalent/operator-generic:v1.9.10-eksa.1": failed to resolve reference "public.ecr.aws/isovalent/operator-generic:v1.9.10-eksa.1": failed to do request: Head "https://public.ecr.aws/v2/isovalent/operator-generic/manifests/v1.9.10-eksa.1": dial tcp 99.83.145.10:443: i/o timeout
  Normal   BackOff  2m58s (x331 over 87m)  kubelet  Back-off pulling image "public.ecr.aws/isovalent/operator-generic:v1.9.10-eksa.1"

$ kubectl describe pod -l k8s-app=cilium -n kube-system

...
Events:
  Type     Reason   Age                  From     Message
  ----     ------   ----                 ----     -------
  Warning  Failed   25m (x8 over 90m)    kubelet  Failed to pull image "public.ecr.aws/isovalent/cilium:v1.9.10-eksa.1": rpc error: code = Unknown desc = failed to pull and unpack image "public.ecr.aws/isovalent/cilium:v1.9.10-eksa.1": failed to resolve reference "public.ecr.aws/isovalent/cilium:v1.9.10-eksa.1": failed to do request: Head "https://public.ecr.aws/v2/isovalent/cilium/manifests/v1.9.10-eksa.1": dial tcp 75.2.101.78:443: i/o timeout
  Normal   BackOff  17s (x351 over 89m)  kubelet  Back-off pulling image "public.ecr.aws/isovalent/cilium:v1.9.10-eksa.1"
```

But those images are not available on the registry. The `import-images` command imported the following images to the registry:

```text
.../isovalent/cilium:v1.9.11-eksa.1
.../isovalent/operator-generic:v1.9.11-eksa.1
```

As you can see, this is a different version.

Proof:

Listing available images using `imgpkg`, returns the following output:

```text
$ imgpkg tag list -i it-harboreksa-01.terasky.demo:443/isovalent/operator-generic --registry-verify-certs=false

Tags

Name  
v1.9.11-eksa.1  

1 tags

Succeeded

$ imgpkg tag list -i it-harboreksa-01.terasky.demo:443/isovalent/cilium --registry-verify-certs=false

Tags

Name  
v1.9.11-eksa.1  

1 tags

Succeeded
```

Since Cilium is not running, the nodes never become ready and the rest of the deployment fails.

```text
$ kubectl get nodes

NAME             STATUS     ROLES                  AGE    VERSION
10.100.138.134   NotReady   <none>                 98m    v1.21.9
10.100.138.135   NotReady   <none>                 98m    v1.21.9
10.100.138.35    NotReady   control-plane,master   100m   v1.21.9
10.100.138.68    NotReady   control-plane,master   98m    v1.21.9

$ kubectl get pods -A

NAMESPACE          NAME                                                       READY   STATUS                  RESTARTS   AGE
cert-manager       cert-manager-54f68f548d-dccmg                              0/1     Pending                 0          98m
cert-manager       cert-manager-cainjector-c8f966cb7-l2rmr                    0/1     Pending                 0          98m
cert-manager       cert-manager-webhook-d9649cc7d-h6bb7                       0/1     Pending                 0          98m
eksa-diagnostics   vsphereclusteridentities.infrastructure.cluster.x-k8s.io   0/1     Pending                 0          59m
kube-system        cilium-4xn9b                                               0/1     Init:ErrImagePull       0          98m
kube-system        cilium-9txbv                                               0/1     Init:ErrImagePull       0          98m
kube-system        cilium-operator-86d59d5c88-7tkl5                           0/1     ImagePullBackOff        0          98m
kube-system        cilium-operator-86d59d5c88-nmqnk                           0/1     ImagePullBackOff        0          98m
kube-system        cilium-tmjpp                                               0/1     Init:ImagePullBackOff   0          98m
kube-system        cilium-tmlrf                                               0/1     Init:ImagePullBackOff   0          98m
kube-system        coredns-fd9559446-dhxnd                                    0/1     Pending                 0          100m
kube-system        coredns-fd9559446-rsvb7                                    0/1     Pending                 0          100m
kube-system        kube-apiserver-10.100.138.35                               1/1     Running                 0          100m
kube-system        kube-apiserver-10.100.138.68                               1/1     Running                 0          98m
kube-system        kube-controller-manager-10.100.138.35                      1/1     Running                 0          100m
kube-system        kube-controller-manager-10.100.138.68                      1/1     Running                 0          98m
kube-system        kube-proxy-8fxdb                                           1/1     Running                 0          100m
kube-system        kube-proxy-hlm6m                                           1/1     Running                 0          98m
kube-system        kube-proxy-krdlp                                           1/1     Running                 0          98m
kube-system        kube-proxy-wcl4w                                           1/1     Running                 0          99m
kube-system        kube-scheduler-10.100.138.35                               1/1     Running                 0          100m
kube-system        kube-scheduler-10.100.138.68                               1/1     Running                 0          98m
kube-system        kube-vip-10.100.138.35                                     1/1     Running                 0          100m
kube-system        kube-vip-10.100.138.68                                     1/1     Running                 0          98m
kube-system        vsphere-cloud-controller-manager-57v2k                     1/1     Running                 2          98m
kube-system        vsphere-cloud-controller-manager-6bhg5                     1/1     Running                 2          98m
kube-system        vsphere-cloud-controller-manager-ddd9l                     1/1     Running                 1          100m
kube-system        vsphere-cloud-controller-manager-n6q2r                     1/1     Running                 2          99m
kube-system        vsphere-csi-controller-6ddb47565c-hz2gc                    0/5     Pending                 0          100m
kube-system        vsphere-csi-node-4lq4p                                     0/3     ContainerCreating       0          98m
kube-system        vsphere-csi-node-4stlm                                     0/3     ContainerCreating       0          98m
kube-system        vsphere-csi-node-b98tv                                     0/3     ContainerCreating       0          100m
kube-system        vsphere-csi-node-jd4s5                                     0/3     ContainerCreating       0          99m
```

Looking at the manifests under `eks-anywhere-downloads`, I see that `eks-anywhere-downloads/1.21/cilium/cilium.yaml` does incorrectly point to `v1.9.10-eksa.1` although `eks-anywhere-downloads/manifest.yaml` points to `v1.9.11-eksa.1`.

Here's the content of `eks-anywhere-downloads/1.21/cilium/cilium.yaml`:
https://gist.github.com/itaytalmi/c00b03739e6a7c0dc1bdaae927fb1088

And the content of `eks-anywhere-downloads/manifest.yaml`:
https://gist.github.com/itaytalmi/d04a34077f13469a593109ca3b5c4e0e

**What you expected to happen**:

The deployment is supposed to pull all images from the private registry and complete successfully in this air-gapped environment, since I have imported all images using the `import-images` command downloaded the manifests using the `download artifacts` command.

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce it, you need an air-gapped environment.
The steps I took:

a. Imported the images to the private registry:

```bash
eksctl anywhere import-images -f cluster-spec.yaml
```

b. Downloaded and extracted the artifacts/manifests:

```bash
eksctl anywhere download artifacts -f cluster-spec.yaml
tar zxf eks-anywhere-downloads.tar.gz
```

c. Deployed the cluster:

```bash
eksctl anywhere create cluster -f cluster-spec.yaml --bundles-override=eks-anywhere-downloads/manifest.yaml
```

My cluster config:

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: eksa-custom-mgmt
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "10.100.138.210"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: eksa-custom-mgmt-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: eksa-custom-mgmt
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: eksa-custom-mgmt-etcd
  kubernetesVersion: "1.21"
  managementCluster:
    name: eksa-custom-mgmt
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: eksa-custom-mgmt
    name: md-0
  registryMirrorConfiguration:
    endpoint: it-harboreksa-01.terasky.demo
    port: 443
    caCertContent: |
      -----BEGIN CERTIFICATE-----
      MIIFVTCCBD2gAwIBAgITUw ....
      -----END CERTIFICATE-----
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: eksa-custom-mgmt
spec:
  datacenter: "Demo-Datacenter"
  insecure: false
  network: "itay-eksa-offline"
  server: "demo-vc-01.terasky.demo"
  thumbprint: "26:3A:FF:3E:01:84:36:F5:BC:18:80:27:0E:14:59:AB:8E:1B:9E:53"
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: eksa-custom-mgmt-cp
spec:
  datastore: "vsanDatastore"
  diskGiB: 25
  folder: "/Demo-Datacenter/vm/LABS/Itay/EKSA"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  template: "/Demo-Datacenter/vm/LABS/Itay/EKSA/bottlerocket-vmware-k8s-1.21-x86_64-1.6.0-9749af99"
  resourcePool: "/Demo-Datacenter/host/Demo-Cluster/Resources"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2E...
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: eksa-custom-mgmt
spec:
  datastore: "vsanDatastore"
  diskGiB: 25
  folder: "/Demo-Datacenter/vm/LABS/Itay/EKSA"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  template: "/Demo-Datacenter/vm/LABS/Itay/EKSA/bottlerocket-vmware-k8s-1.21-x86_64-1.6.0-9749af99"
  resourcePool: "/Demo-Datacenter/host/Demo-Cluster/Resources"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2E...
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: eksa-custom-mgmt-etcd
spec:
  datastore: "vsanDatastore"
  diskGiB: 25
  folder: "/Demo-Datacenter/vm/LABS/Itay/EKSA"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  template: "/Demo-Datacenter/vm/LABS/Itay/EKSA/bottlerocket-vmware-k8s-1.21-x86_64-1.6.0-9749af99"
  resourcePool: "/Demo-Datacenter/host/Demo-Cluster/Resources"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2E...
```

Anything else we need to know?**:

I'm using VMware Harbor as the private registry.

To create the required repositories as instructed on the EKS-A documentation, I used the following:

```bash
HARBOR_HOSTNAME=it-harboreksa-01.terasky.demo
HARBOR_PASSWORD=your_password

declare -a projects=("bottlerocket" "eks-anywhere" "eks-distro" "isovalent")
for project in "${projects[@]}"
do
    curl -k -H "Content-Type: application/json" \
    -u "admin:$HARBOR_PASSWORD" \
    -X POST "https://$HARBOR_HOSTNAME/api/v2.0/projects" \
    -d '{"project_name": '\"${project}\"', "public": true}'
done
```

**Environment**:
- EKS Anywhere Release: `0.7.2`
- EKS Distro Release:  `eks-d-1-21-9-eks-a-7`
- eksctl version: `0.85.0`
