### ISSUE TITLE
Add status to Cluster object

### ISSUE THREAD

**Issue by vivek-koppuru** [aws/eks-anywhere#165]
Add some fields to the status for the Cluster that might be useful for a user to get information about the status of their EKS-A cluster object. Below is just an example of what the status object can look like:

```
status:
  version: ""
  controlPlaneMachineCount: 1
  workerNodeGroups:
  - machineCount: 1
  externalEtcdMachineCount: 1
  gitOps:
    gitOpsRef: ""
    repository: ""
    owner: ""
    branch: ""
    latestCommit: ""
    status: pending/synced/paused/unavailable # reflects whether our eks-a controller is syncing with the repository or not
  bundlesRef: "" # References a bundle CRD that contains information about all versions of container images that we rely on
  licenseRef: ""
```
