### ISSUE TITLE
Add reference creds for VCenter and GitOps in Cluster spec

### ISSUE THREAD

**Issue by vivek-koppuru** [aws/eks-anywhere#166]
The three environment variables that can be set for a EKS-A cluster are the VSphere username and password as well as the GitHub token (if GitOps is enabled). These secrets can be loaded on the created Kubernetes cluster as a reference from the Cluster spec. Below are just examples of how that might look:

VSphereDatacenterConfig:
```
apiVersion: anywhere.eks.amazonaws.com/v1
kind: VSphereDatacenterConfig
metadata:
  name: test-datacenter
  namespace: default
spec:
  ...
  credentialsRef: # populated by CLI when passed in as env var
   secretName: "" # needs to be a basic-auth type secret
```

GitOpsConfig:
```
apiVersion: anywhere.eks.amazonaws.com/v1
kind: GitOpsConfig
metadata:
  name: test-gitops
  namespace: default
spec:
  flux:
    github:
      ...
      authTokenRef: # populated by CLI if passed in as flag/env var
        secretName: "" # needs to be an opaque secret
        secretKey: "personal-access-token"
```
