### ISSUE TITLE
[EKS-A 0.8.1] Fail to create mgmt cluster when using private image repository (harbor) because cert-manager time out error

### ISSUE THREAD

**Issue by joe2709** [aws/eks-anywhere#1825]
### What happened:
I'm trying to deploy new cluster using registry mirror and bundles-override option in air-gap environment.
But cert-manger pod images cannot be pulled from the private image registry(harbor) on bootstrap cluster.

I can see the registry mirror configuration in config.toml file on bootstrap cluster container as set to eksa-mgmt-cluster.yaml file

- eksa-mgmt-cluster.yaml
```
registryMirrorConfiguration:
    endpoint: krharbor1.tcis.com
    port: 443
    caCertContent: |
      -----BEGIN CERTIFICATE-----
      MIIF+DCCA...........
      -----END CERTIFICATE-----
```

- /etc/containerd/config.toml on bootstrap cluster container
```
root@eksaams2:~/eks-anywhere/eksanywher_0.8.1# docker ps
CONTAINER ID   IMAGE                                                                                        COMMAND                  CREATED              STATUS              PORTS                       NAMES
48ba1ae33538   krharbor1.tcis.com:443/eks-anywhere/kubernetes-sigs/kind/node:v1.22.6-eks-d-1-22-4-eks-a-8   "/usr/local/bin/entr…"   About a minute ago   Up About a minute   127.0.0.1:45899->6443/tcp   mgmt-eks-a-cluster-control-plane
4006d5dcfef2   krharbor1.tcis.com:443/eks-anywhere/cli-tools:v0.7.2-eks-a-8                                 "sleep infinity"         About a minute ago   Up About a minute                               eksa_1649752956470157350

root@eksaams2:~/eks-anywhere/eksanywher_0.8.1# docker exec -it  mgmt-eks-a-cluster-control-plane sh

sh-4.2# cat /etc/containerd/config.toml
....
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."public.ecr.aws"]
          endpoint = ["https://krharbor1.tcis.com:443"]
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."krharbor1.tcis.com:443"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."krharbor1.tcis.com:443".tls]
            insecure_skip_verify = false
            ca_file = "/etc/containerd/certs.d/krharbor1.tcis.com:443/ca.crt"
            cert_file = ""
            key_file = ""
...
```

- error to pull image for cert-manager on bootstrap cluster container
```
sh-4.2# kubectl get pod -A
NAMESPACE            NAME                                                       READY   STATUS              RESTARTS   AGE
cert-manager         cert-manager-76cd6884cc-kx2ff                              0/1     ErrImagePull        0          40s
cert-manager         cert-manager-cainjector-7df6c99858-75ttw                   0/1     ContainerCreating   0          40s
cert-manager         cert-manager-webhook-6bfb8f8cb5-87qxr                      0/1     ContainerCreating   0          40s


sh-4.2# kubectl -n cert-manager describe pod cert-manager-76cd6884cc-kx2ff 
Name:         cert-manager-76cd6884cc-kx2ff
....
  Warning  Failed            38s                kubelet            Error: ErrImagePull
  Normal   BackOff           37s                kubelet            Back-off pulling image "public.ecr.aws/eks-anywhere/jetstack/cert-manager-controller:v1.5.3-eks-a-8"
  Warning  Failed            37s                kubelet            Error: ImagePullBackOff
  Normal   Pulling           23s (x2 over 48s)  kubelet            Pulling image "public.ecr.aws/eks-anywhere/jetstack/cert-manager-controller:v1.5.3-eks-a-8"
sh-4.2# 
```

Since cert-manager pod isn't deployed, cluster creation is failed.
I think there is a need  username and password for pulling image from harbor.
I tried to add registry configs auth for harbor `manually` as below, then image for cert-manager is pulled successfully 

```
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."public.ecr.aws"]
          endpoint = ["https://krharbor1.tcis.com:443"]
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."krharbor1.tcis.com:443"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."krharbor1.tcis.com:443".auth]
            username = "admin"
            password = "xxxxxxxxx"
            auth = ""
            identitytoken = ""
          [plugins."io.containerd.grpc.v1.cri".registry.configs."krharbor1.tcis.com:443".tls]
            insecure_skip_verify = false
            ca_file = "/etc/containerd/certs.d/krharbor1.tcis.com:443/ca.crt"
            cert_file = ""
            key_file = ""
```

- pull image for cert-manager successfully
```
sh-4.2# kubectl get pod -A
NAMESPACE                           NAME                                                             READY   STATUS              RESTARTS   AGE
cert-manager                        cert-manager-76cd6884cc-kx2ff                                    1/1     Running             0          4m37s
cert-manager                        cert-manager-cainjector-7df6c99858-75ttw                         1/1     Running             0          4m37s
cert-manager                        cert-manager-webhook-6bfb8f8cb5-87qxr                            1/1     Running             0          4m37s
```

### What you expected to happen:
When username and password was exported as below 
That will insert to `config.toml` in `bootstrap cluster container` but it is used only for `helm registry login`.

```
export REGISTRY_USERNAME=admin
export REGISTRY_PASSWORD=xxxxxxx

4899 helm registry login krharbor1.tcis.com --username admin --password ***** --insecure"}
WARNING: Using --password via the CLI is insecure. Use --password-stdin.
2022-04-11T13:35:01.087+0900	V6	Executing command	{"cmd": "/usr/bin/docker exec -i -e HELM_EXPERIMENTAL_OCI=1 eksa_1649651528516424899 helm pull oci://public.ecr.aws/isovalent/cilium --version 1.9.13-eksa.2 --insecure-skip-tls-verify"}
2022-04-11T13:35:04.235+0900	V0	Pushing	{"chart": "cilium-1.9.13-eksa.2.tgz"}
2022-04-11T13:35:04.235+0900	V6	Executing command	{"cmd": "/usr/bin/docker exec -i -e HELM_EXPERIMENTAL_OCI=1 eksa_1649651528516424899 helm push cilium-1.9.13-eksa.2.tgz oci://krharbor1.tcis.com/cilium-chart --insecure-skip-tls-verify"}

```

There is a guide for set `username` and `password` for `auth` in `config.toml` file on `OVA Template` 
[Configure VM with cloud-init and the VMX GuestInfo datasource](https://anywhere.eks.amazonaws.com/docs/reference/vsphere/customize-ovas/#configure-vm-with-cloud-init-and-the-vmx-guestinfo-datasource)
but there is no a guide for bootstrap cluster container  
- **I hope to add variables for username and password to clustser.yaml as below** 
```
registryMirrorConfiguration:
    endpoint: krharbor1.tcis.com
    port: 443
    caCertContent: |
      -----BEGIN CERTIFICATE-----
      MIIF+DCCA...........
      -----END CERTIFICATE-----
     authUserName: "admin"
     authPassWord:  "xxxxxxxx"
```

### How to reproduce it (as minimally and precisely as possible):
you need air-gap environment and using `harbor` using `private mode project` for image registry

a. generate cluster.yaml file 
```
eksctl anywhere generate clusterconfig mgmt --provider vsphere > eksa-mgmt-cluster.yaml
```

b. import image to private registry(harbor)
```
export REGISTRY_USERNAME=admin
export REGISTRY_PASSWORD=xxxxxxx
eksctl anywhere import-images -f eksa-mgmt-cluster.yaml
```

c. download artifacts file 
```
eksctl anywhere download artifacts -f eksa-mgmt-cluster.yaml
tar zxf eks-anywhere-downloads.tar.gz
```

d. deploy mgmt cluster
```
eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml--bundles-override eks-anywhere-downloads/manifest.yaml  -v9
```

- Cluster config file
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "xxx.xxx.xxx.xxx"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: mgmt
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-etcd
  kubernetesVersion: "1.22"
  managementCluster:
    name: mgmt
  registryMirrorConfiguration:
    endpoint: krharbor1.tcis.com
    port: 443
    caCertContent: |
      -----BEGIN CERTIFICATE-----
      MIIF+DC...
      -----END CERTIFICATE-----
  workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt
    name: router
  - count: 1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt
    name: infra
  - count: 1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt
    name: worker

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: mgmt
spec:
  datacenter: "Songdo"
  insecure: true
  network: "/Songdo/network/VM Network - VLAN120"
  server: "vc67.tcis.com"
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-cp
spec:
  datastore: "/Songdo/datastore/V7000-02"
  diskGiB: 25
  folder: "/Songdo/vm/TCIS-EKS-ANYWHERE/MGMT-EKS-D-1-22-4"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  resourcePool: "*/Resources"
  template: "/Songdo/vm/TCIS-EKS-ANYWHERE/TEMPLATE/ubuntu-v1.22.6-eks-d-1-22-4-eks-a-8-amd64"
  users:
  - name: root
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt
spec:
  datastore: "/Songdo/datastore/V7000-02"
  diskGiB: 25
  folder: "/Songdo/vm/TCIS-EKS-ANYWHERE/MGMT-EKS-D-1-22-4"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  resourcePool: "*/Resources"
  template: "/Songdo/vm/TCIS-EKS-ANYWHERE/TEMPLATE/ubuntu-v1.22.6-eks-d-1-22-4-eks-a-8-amd64"
  users:
  - name: root
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-etcd
spec:
  datastore: "/Songdo/datastore/V7000-02"
  diskGiB: 25
  folder: "/Songdo/vm/TCIS-EKS-ANYWHERE/MGMT-EKS-D-1-22-4"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  resourcePool: "*/Resources"
  template: "/Songdo/vm/TCIS-EKS-ANYWHERE/TEMPLATE/ubuntu-v1.22.6-eks-d-1-22-4-eks-a-8-amd64"
  users:
  - name: root
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc...

```

### Anything else we need to know?:

- Refer to image for project of harbor registry
- Project of harbor should be set private mode in our environment.
- This is `open source registry harbor` instead `VMware harbor`.

![image](https://user-images.githubusercontent.com/28323222/163101668-103f7ee5-4c9b-4190-a22c-1df5ee11f70e.png)

Environment:

EKS Anywhere Release: v0.8.1
EKS Distro Release: eks-d-1-22-4-eks-a-8
eksctl version: 0.92.0
