### ISSUE TITLE
EKS cluster creation failing to pass condition=ControlPlaneReady 

### ISSUE THREAD

**Issue by ianatmedacist** [aws/eks-anywhere#1926]
**What happened**:
When creating a net new cluster it fails on the step

and the controlplane node reports the following as the last error when I run `journalctl -u kubelet --no-pager`
`Invalid attach limit value 0 cannot be added to CSINode object for "csi.vsphere.vmware.com"`

**What you expected to happen**:
The control plane would start and the CSINode does not error out.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster with the provided YAML

**Anything else we need to know?**:
This does not seem related to the OS or kubernetes version choice as it is reproducible on all of them

**Environment**:
eksctl 0.94.0
eksctl anywhere v0.8.2 and v0.8.1
vcenter 7.0.3.003
docker version: 20.10.14
host: ubuntu 20.04

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: basic-tiny
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "172.16.50.5"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: basic-tiny-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: basic-tiny
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: basic-tiny-etcd
  kubernetesVersion: "1.20"
  managementCluster:
    name: basic-tiny
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: basic-tiny
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: basic-tiny
spec:
  datacenter: "sandbox"
  insecure: false
  network: "DPG_1"
  server: "vcenter.org.com"
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: basic-tiny-cp
spec:
  datastore: "datastore"
  diskGiB: 25
  folder: "folder"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  resourcePool: "Resources"

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: basic-tiny
spec:
  datastore: "datastore"
  diskGiB: 25
  folder: "folders"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  resourcePool: "Resources"

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: basic-tiny-etcd
spec:
  datastore: "datastore"
  diskGiB: 25
  folder: "folders"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "Resources"

---
```
