### ISSUE TITLE
Control Plane machine is on Provisioned State while deploy EKS Anywhere on vSphere 7  

### ISSUE THREAD

**Issue by haseebsultan** [aws/eks-anywhere#1953]
I am trying to deploy eks-anywhere on vSphere 7, following https://anywhere.eks.amazonaws.com/docs/getting-started/production-environment/ but facing an issue, my control plane machine is on  Provisioned state not coming to Running state

```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: ""
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: mgmt
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-etcd
  kubernetesVersion: "1.22"
  managementCluster:
    name: mgmt
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: mgmt
spec:
  datacenter: ""
  insecure: true
  network: ""
  server: ""
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-cp
spec:
  datastore: ""
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt
spec:
  datastore: "workload_share_wdc04taaxcm_SCp6a"
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-etcd
spec:
  datastore: "workload_share_wdc04taaxcm_SCp6a"
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
```

Applying yaml by following command

`eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml`

Following Screen Shot for reference:

![image](https://user-images.githubusercontent.com/38536290/165521191-763477b7-e58d-4d5a-960b-90467dee5968.png)

Kindly review the yaml and let me know, if there is any issue.

Thanks
.
