### ISSUE TITLE
Add physicalNetworkConnector default when generating snow cluster config

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#2166]
**What would you like to be added**:

`eksctl anywhere generate clusterconfig -p snow test-cluster` should include the default `physicalNetworkConnector` field

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: SnowMachineConfig
metadata:
  name: aa
spec:
  amiID: ""
  instanceType: sbe-c.large
  sshKeyName: default
  physicalNetworkConnector: SFP_PLUS # to add
```

**Why is this needed**:
