### ISSUE TITLE
Documentation update for clusterspec/vsphere.md

### ISSUE THREAD

**Issue by smarsh-tim** [aws/eks-anywhere#2369]
**What happened**:
https://github.com/aws/eks-anywhere/blob/main/docs/content/en/docs/reference/clusterspec/vsphere.md has some mismatched documentation.

The generic template reflects:
```yaml
clusterNetwork:
      cniConfig:
         cilium: {}
      pods:
         cidrBlocks:
```

But later in the documentation is still reflects the deprecated value:

> ### clusterNetwork.cni (required)
> CNI plugin to be installed in the cluster. The only supported value at the moment is cilium.

**What you expected to happen**:

Documentation corrected to reflect the current supported and non-deprecated values.

**Comment by TerryHowe** [comment]
That is what I have
```
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
```

What version of the CLI do you have? There was a change around there around v0.7 I think. I'm running v0.9.x
