### ISSUE TITLE
Add KCP and MD ready checks to ensure cluster creation is completed

### ISSUE THREAD

**Issue by mrajashree** [aws/eks-anywhere#279]
Create cluster uses [nodeRef](https://github.com/aws/eks-anywhere/blob/5c54f5b798ee07cfc63e86577a32ca606d32a89a/pkg/clustermanager/cluster_manager.go#L200) as a check to see if all nodes are ready. Along with that we should also validate the [KCP replicas](https://github.com/aws/eks-anywhere/blob/5c54f5b798ee07cfc63e86577a32ca606d32a89a/pkg/clustermanager/cluster_manager.go#L284) for controlplane nodes and [MD replicas](https://github.com/aws/eks-anywhere/blob/5c54f5b798ee07cfc63e86577a32ca606d32a89a/pkg/clustermanager/cluster_manager.go#L299) for worker nodes post create like we do post upgrade. This is because there could be cases where nodeRef is set and node itself is healthy but the pods are unhealthy. Checking for replicas on KCP/MD can catch such cases too.

For instance these are the status fields on a control plane machine from a failed e2e test:
```
status:
  addresses:
  - address: x.x.x.x
    type: ExternalIP
  bootstrapReady: true
  conditions:
  - lastTransitionTime: "2021-09-22T15:55:24Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-09-22T15:55:29Z"
    message: Missing node
    reason: PodFailed
    severity: Error
    status: "False"
    type: APIServerPodHealthy
  - lastTransitionTime: "2021-09-22T15:54:53Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2021-09-22T15:55:29Z"
    message: Missing node
    reason: PodFailed
    severity: Error
    status: "False"
    type: ControllerManagerPodHealthy
  - lastTransitionTime: "2021-09-22T15:55:24Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2021-09-22T15:54:55Z"
    status: "True"
    type: NodeHealthy
  - lastTransitionTime: "2021-09-22T15:55:29Z"
    message: Missing node
    reason: PodFailed
    severity: Error
    status: "False"
    type: SchedulerPodHealthy
  infrastructureReady: true
  lastUpdated: "2021-09-22T15:55:25Z"
  nodeRef:
    apiVersion: v1
    kind: Node
    name: x.x.x.x
    uid: 03efca98-7d28-4419-aec5-8000fe76a8c0
  observedGeneration: 1
  phase: Running
```
And this is the KCP for the cluster:
```
kubectl get kcp -A
NAMESPACE     NAME        INITIALIZED   API SERVER AVAILABLE   VERSION              REPLICAS   READY   UPDATED   UNAVAILABLE
eksa-system   eksa-test   true          true                   v1.20.7-eks-1-20-6   2          1       2         1
```
