### ISSUE TITLE
Validation failed with "please specify a datacenter" error though I have provided correct datacenter name

### ISSUE THREAD

**Issue by miryalasaigoutham** [aws/eks-anywhere#2798]
Hi Team,

While creating the cluster in vSphere, validation failed due to the below error though I gave the correct data centre details.

2022-07-26T23:52:42.307+0530    V0      ❌ Validation failed     {"validation": "vsphere Provider setup is valid", "error": "failed setting default values for vsphere machine configs: failed creating library for new template: creating library eks-a-templates: govc: please specify a datacenter\n", "remediation": ""}

Please let me know if I'm making a mistake.

Thanks and Regards
Sai Goutham Miryala

**Comment by miryalasaigoutham** [comment]
But it says Datacenter validated, when I executed create cluster command

>> eksctl anywhere create cluster -f eksa-vsphere-mgmt-cluster.yaml     
Warning: The recommended size of an external etcd cluster is 3 or 5
Warning: VSphereDatacenterConfig configured in insecure mode
Warning: The recommended size of an external etcd cluster is 3 or 5
Performing setup and validations
Warning: VSphereDatacenterConfig configured in insecure mode
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
❌ Validation failed     {"validation": "vsphere Provider setup is valid", "error": "failed setting default values for vsphere machine configs: failed creating library for new template: creating library eks-a-templates: govc: please specify a datacenter\n", "remediation": ""}
✅ Validate certificate for registry mirror
✅ Create preflight validations pass
Error: validations failed

**Comment by TerryHowe** [comment]
Does your datacenter config look something like:
```
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: tlhowe
spec:
  datacenter: "Datacenter"
  network: "/Datacenter/network/VM Network"
  server: 10.61.250.74
  thumbprint: ""
```
