### ISSUE TITLE
cluster upgrade systematically fails with `aws iam identity provider is immutable`

### ISSUE THREAD

**Issue by sleterrier** [aws/eks-anywhere#2830]
**What happened**:
`eksctl anywhere upgrade cluster` systematically fails validation due to `“Validation failed    {"validation": "upgrade preflight validations pass", "error": "validation failed with 1 errors: aws iam identity provider is immutable", "remediation": ""}”` even when no changes are made to `AWSIamConfig` block.

**How to reproduce it (as minimally and precisely as possible)**:
```
eksctl anywhere create cluster -f mgmt-cluster.yaml
  🎉 Cluster created!

eksctl anywhere create cluster -f workload-cluster.yaml --kubeconfig mgmt-cluster/mgmt-cluster-eks-a-cluster.kubeconfig
  🎉 Cluster created!

eksctl anywhere upgrade cluster -f workload-cluster.yaml --kubeconfig mgmt-cluster/mgmt-cluster-eks-a-cluster.kubeconfig
  ❌ Validation failed {"validation": "upgrade preflight validations pass", "error": "validation failed with 1 errors: aws iam identity provider is immutable", "remediation": ""}
```

Which unless I am missing something, leaves us with:
- Either something is atypical/wrong with our `*-cluster.yaml`'s 👇 
- Or we are hitting a generic bug, which seems unlikely given the absence of similar reports on the issues board...

Any pointer would be greatly appreciated.

**Anything else we need to know?**:
Here are the (truncated, only showing relevant elements) EKS-A clusters configs:

##### mgmt-cluster.yaml
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt-cluster
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 172.20.0.0/16
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 10.1.1.1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-cluster-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: mgmt-cluster
  gitOpsRef:
    kind: FluxConfig
    name: mgmt-cluster
  identityProviderRefs:
  - kind: AWSIamConfig
    name: mgmt-cluster-aws-auth
  - kind: OIDCConfig
    name: mgmt-cluster-oidc-auth
  kubernetesVersion: "1.21"
  managementCluster:
    name: mgmt-cluster
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-cluster-worker
    name: worker

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: AWSIamConfig
metadata:
  name: mgmt-cluster-aws-auth
  namespace: default
spec:
  awsRegion: us-gov-west-1
  backendMode:
  - EKSConfigMap
  mapRoles:
  - groups:
    - system:masters
    roleARN: arn:aws-us-gov:iam::012345678910:role/AWSReservedSSO_admin_d58d408acb82131b
    username: adminuser:{{SessionName}}
  partition: aws-us-gov

---
```

##### workload-cluster.yaml
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by: mgmt-cluster
  name: workload-cluster
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 172.20.0.0/16
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 10.1.2.1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload-cluster-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: workload-cluster
  identityProviderRefs:
  - kind: AWSIamConfig
    name: workload-cluster-aws-auth
  - kind: OIDCConfig
    name: workload-cluster-oidc-auth
  kubernetesVersion: "1.21"
  managementCluster:
    name: mgmt-cluster
  workerNodeGroupConfigurations:
  - count: 6
    labels:
      company.com/node-type: generic
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload-cluster-worker-generic
    name: worker-generic

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: AWSIamConfig
metadata:
  name: workload-cluster-aws-auth
  namespace: default
spec:
  awsRegion: us-gov-west-1
  backendMode:
  - EKSConfigMap
  mapRoles:
  - groups:
    - system:masters
    roleARN: arn:aws-us-gov:iam::012345678910:role/AWSReservedSSO_admin_d58d408acb82131b
    username: {{SessionName}}
  - groups:
    - aws-sso:dev-account:dev-users
    roleARN: arn:aws-us-gov:iam::123456789100:role/AWSReservedSSO_dev-user_d58d408acb82131b
    username: {{SessionName}}
  partition: aws-us-gov

---
```

**Environment**:
- EKS Anywhere Release: v0.10.0

**Comment by sleterrier** [comment]
We reproduced the issue with a brand new management cluster:
```
eksctl anywhere create cluster -f mgmt-cluster-test-cluster.yaml
  🎉 Cluster created!

eksctl anywhere create cluster -f workload-cluster.yaml --kubeconfig mgmt-cluster-test/mgmt-cluster-test-eks-a-cluster.kubeconfig
  🎉 Cluster created!

eksctl anywhere upgrade cluster -f workload-cluster.yaml --kubeconfig mgmt-cluster-test/mgmt-cluster-test-eks-a-cluster.kubeconfig
  ❌ Validation failed {"validation": "upgrade preflight validations pass", "error": "validation failed with 1 errors: aws iam identity provider is immutable", "remediation": ""}
```

Which unless I am missing something, leaves us with:
- Either something is atypical/wrong with the above `*-cluster.yaml` ☝️ 
- Or this is a generic bug affecting everyone. Which seems unlikely given the absence of similar reports on the issues board.

Please advise.

**Comment by pokearu** [comment]
@sleterrier Thanks for using EKS-A! 

I tried to reproduce the issue on our side using the EKS-A release `v0.10.0`. But i am not running into the same error on my end.

```
eksctl anywhere create cluster -f ramaliar-ubuntu-management-cluster.yaml

eksctl anywhere create cluster -f ramaliar-ubuntu-workload-cluster.yaml --kubeconfig ./ramaliar-ubuntu-management/ramaliar-ubuntu-management-eks-a-cluster.kubeconfig

eksctl anywhere upgrade cluster -f ramaliar-ubuntu-workload-cluster.yaml --kubeconfig ./ramaliar-ubuntu-management/ramaliar-ubuntu-management-eks-a-cluster.kubeconfig
```

The upgrade does run successfully. Just to confirm I ran `upgrade` with an unmodified `ramaliar-ubuntu-workload-cluster.yaml` file. It runs through the various checks and reports there is nothing to upgrade.

Could you please check if the AWSIamConfig object `workload-cluster-aws-auth` on the management cluster was manually modified?  `AWSIamConfig` is partially mutable i.e. we allow modification of `mapRoles` and `mapUsers` via upgrade or GitOps.

**Comment by sleterrier** [comment]
Hi @pokearu, thank you for looking into this! Much appreciated.

I confirm the `AWSIamConfig` object `workload-cluster-aws-auth` on the management cluster is untouched. 

As a matter of fact, I have just reproduced the issue on a brand new management cluster itself:

```
eksctl anywhere create cluster -f mgmt-cluster.yaml
  🎉 Cluster created!
eksctl anywhere upgrade cluster -f mgmt-cluster.yaml
  ❌ Validation failed    {"validation": "upgrade preflight validations pass", "error": "validation failed with 1 errors: aws iam identity provider is immutable", "remediation": ""}
```
with:
###### mgmt-cluster.yaml
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt-cluster
  namespace: default
spec:
...
  identityProviderRefs:
  - kind: AWSIamConfig
    name: mgmt-cluster-aws-auth
  - kind: OIDCConfig
    name: mgmt-cluster-oidc-auth
```


HOWEVER, if we create the management cluster without the `identityProviderRefs OIDCConfig`:
###### mgmt-cluster.yaml
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt-cluster
  namespace: default
spec:
...
  identityProviderRefs:
  - kind: AWSIamConfig
    name: mgmt-cluster-aws-auth
```

The validation succeeds and the upgrade is attempted:
```
eksctl anywhere create cluster -f mgmt-cluster.yaml
  🎉 Cluster created!
eksctl anywhere upgrade cluster -f mgmt-cluster.yaml
  ✅ Upgrade preflight validations pass
  No upgrades needed from cluster spec
```

**Comment by pokearu** [comment]
Oh thank you for testing! 

My bad I did have only `AWSIamConfig` when i ran my tests. Let me check to see if that makes a difference on my side as well.

**Comment by pokearu** [comment]
@sleterrier Thanks for pointing out the issue. Looks like we need a small fix in the validation logic. Will update shortly.

**Comment by pokearu** [comment]
@sleterrier As a temporary workaround while we get a fix into the next release, you can have both `OIDCConfig ` and `AWSIamConfig ` providers by swapping out the order i.e. having `AWSIamConfig` second.

```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt-cluster
  namespace: default
spec:
...
  identityProviderRefs:
  - kind: OIDCConfig
    name: mgmt-cluster-oidc-auth
  - kind: AWSIamConfig
    name: mgmt-cluster-aws-auth
```

This should solve the validation issue for you.

**Comment by sleterrier** [comment]
@pokearu: confirmed as a functional workaround. Thank you! 👍

**Comment by sleterrier** [comment]
Unfortunately, upon further testing, this workaround only works for new clusters.
Already existing clusters, created with `AWSIamConfig` in first position, still cannot be upgraded :(
Attempts at modifying the `clusters.anywhere.eks.amazonaws.com` object to swap the providers order is denied with `clusters.anywhere.eks.amazonaws.com "workload-cluster" was not valid: * spec.AWS Iam Config: Invalid value: "AWSIamConfig": field is immutable`.

**Comment by pokearu** [comment]
@sleterrier Thank you for verifying the workaround.

I did some testing on my side as well and I was able to swap the identity providers order on the cluster object for the management cluster.
My cluster yaml originally had
```yaml
  identityProviderRefs:
  - kind: AWSIamConfig
    name: aws-iam-auth-config
  - kind: OIDCConfig
    name: oidc-config
```
and by running edit
```
KUBECONFIG=./ramaliar-ubuntu-management/ramaliar-ubuntu-management-aws.kubeconfig kubectl edit cluster/ramaliar-ubuntu-management
```

The cluster object now has the order swapped.
```yaml
  identityProviderRefs:
  - kind: OIDCConfig
    name: oidc-config
  - kind: AWSIamConfig
    name: aws-iam-auth-config
```

The error message you shared
```
* spec.AWS Iam Config: Invalid value: "AWSIamConfig": field is immutable`
```
Should be triggered when we try and modify the order on the cluster object for a workload cluster, not a management cluster.

But to address your questions, I think the solution would be to wait for our upcoming release. That would have the fixes for upgrade and you should be able to upgrade your existing clusters without any need to swap the order of the identity providers. 
Optionally you could try building off `main` and running the upgrade.
