### ISSUE TITLE
YAML to JSON conversion issue during workload-cluster-init task

### ISSUE THREAD

**Issue by mbelling** [aws/eks-anywhere#2876]
**What happened**:

Ran `eksctl anywhere create cluster -v 9 -f eksa-mgmt-cluster.yaml` got the following error mid-run.

```
2022-08-04T12:40:56.759Z        V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1659616700719857435 kubectl apply -f - --namespace eksa-system --kubeconfig mgmt/gene
rated/mgmt.kind.kubeconfig"}
2022-08-04T12:41:00.062Z        V9      docker  {"stderr": "error: error parsing STDIN: error converting YAML to JSON: yaml: line 9: found unknown escape character\n"}
2022-08-04T12:41:00.062Z        V5      Error happened during retry     {"error": "executing apply: error: error parsing STDIN: error converting YAML to JSON: yaml: line 9: found unknown
escape character\n", "retries": 1}
2022-08-04T12:41:00.062Z        V5      Sleeping before next retry      {"time": "5s"}
```

**What you expected to happen**:
Cluster would be successfully created

**How to reproduce it (as minimally and precisely as possible)**:
Run `eksctl anywhere create cluster -v 9 -f eksa-mgmt-cluster.yaml` with the below YAML file.  Replacing the hostnames, IP addresses, and certificates.

**Anything else we need to know?**:

This is trying to run EKS on our internal vSphere.  I tried manually running the `docker exec` command that was failing from the error message above.  It hung there like it was doing something but did not provide any feedback, and eventually just failed because the eksctl run ended and removed the cluster.  The fact that the command did not return immediately with an error leads me to believe the conversion from YAML to JSON is somehow introducing an invalid escape char.

``` yaml
# eksa-mgmt-cluster.yaml  <--- Not part of file, just giving file name
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - <IP Address block here>
    services:
      cidrBlocks:
      - <IP Address block here>
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: <IP Address here>
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: mgmt
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-etcd
  kubernetesVersion: "1.22"
  managementCluster:
    name: mgmt
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt
    name: md-0
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: mgmt
spec:
  datacenter: "Dev Lab"
  insecure: true
  network: "<domain name here>"
  server: "<server hostname here>"
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-cp
spec:
  datastore: "Synology-Datastore"
  diskGiB: 25
  folder: "EKS"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "<resource pool path here>"
  users:
  - name: capv
    sshAuthorizedKeys:
        - "<key here>"
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt
spec:
  datastore: "Synology-Datastore"
  diskGiB: 25
  folder: "EKS"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "<Resource Path Here>"
  users:
  - name: capv
    sshAuthorizedKeys:
        - "<key here>"
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-etcd
spec:
  datastore: "Synology-Datastore"
  diskGiB: 25
  folder: "EKS"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "<Resource path here>"
  users:
  - name: capv
    sshAuthorizedKeys:
        - "<key here>"
```

``` yaml
# mgmt/generated/mgmt.kind.kubeconfig  <--- Not in file, just file name>
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <Cert here>
    server: <URL>
  name: kind-mgmt-eks-a-cluster
contexts:
- context:
    cluster: kind-mgmt-eks-a-cluster
    user: kind-mgmt-eks-a-cluster
  name: kind-mgmt-eks-a-cluster
current-context: kind-mgmt-eks-a-cluster
kind: Config
preferences: {}
users:
- name: kind-mgmt-eks-a-cluster
  user:
    client-certificate-data: <Cert here>
    client-key-data: <Cert here>
```

**Environment**:
- EKS Anywhere Release:
0.105.0-dev+aa76f1d4.2022-07-08T12:49:09Z
- EKS Distro Release:
