### ISSUE TITLE
Boot hang after "random: crng init done" at worker node(ProLiant XL675d Gen10 Plus w/AMD EPYC 7543)

### ISSUE THREAD

**Issue by SeungyeopShin** [aws/eks-anywhere#2906]
**What happened**: 
Hanging after  random: crng init done" at worker node(ProLiant XL675d Gen10 Plus w/AMD EPYC 7543)
[Screenshot](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F3594b441-e81b-4661-873e-7b7042dbf02c%2FUntitled.png?table=block&id=676dce53-0aa8-489e-bff7-af9804aa95f4&spaceId=b3e98253-660b-4047-a151-a0d9f08cf268&width=2000&userId=402d9c4e-3022-4568-8482-3cb7d46a0635&cache=v2)

**What you expected to happen**:
boot normally

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Server : ProLiant XL675d Gen10 Plus w/AMD EPYC 7543

**Environment**:
- EKS Anywhere Release: 0.10.1
- EKS Distro Release: 1.22-9

**Comment by ptrivedi** [comment]
Hi @SeungyeopShin, what network drivers are present on this server? Are you using RAID? It would be useful if you are able to provide your hardware specifications. Thank you.

**Comment by SeungyeopShin** [comment]
Hi @ptrivedi,
The hardware information is below.

- Network
  - Marvell FastLinQ 41000 Series - 2P 10GbE 10GBASE-T QL41132HLRJ-HC MD2 Adapter - NIC
  -  Intel(R) Ethernet Server Adapter I350-T4(Unused)
- RAID
  - Controller : HPE Smart Array P408i-a SR Gen10
  - OS : RAID 1
  - Data : Non RAID
- GPU
  - Baseboard : NVIDIA HGX A100 8 GPU 80
 
Thanks.

**Comment by danbudris** [comment]
Hey there @SeungyeopShin , we're unable to access the linked screenshot.

Also, if you could provide a sanitized copy of your cluster configuration and the support bundle generated by the EKS A CLI  it would aid in debugging. Thank yoU!

**Comment by SeungyeopShin** [comment]
Hi, @danbudris .
The screen shot is [here](https://drive.google.com/file/d/1kr1K-LfMf3R8BayYJomP2NjRl8FDbaWE/view?usp=sharing)
Hanging is appeared only in GPU(HPE) server.
And my cluster configuration is as below.(xxx means masking) 

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: xxx-eksa
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 3 
    endpoint:
      host: "10.255.xx.xx"
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: xxx-eksa-cp
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: xxx-eksa
  kubernetesVersion: "1.22"
  managementCluster:
    name: xxx-eksa
  workerNodeGroupConfigurations:
    - count: 2
      machineGroupRef:
        kind: TinkerbellMachineConfig
        name: xxx-eksa-worker-default
      name: worker-default
    - count: 1
      machineGroupRef:
        kind: TinkerbellMachineConfig
        name: xxx-eksa-worker-gpu
      name: worker-gpu
  # IAM Authenticator
  identityProviderRefs:
    - kind: AWSIamConfig
      name: aws-iam-auth-config
  podIamConfig:
    serviceAccountIssuer: https://xxx.xxx.xxx

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: AWSIamConfig
metadata:
  name: aws-iam-auth-config
spec:
  awsRegion: "ap-northeast-2"
  backendMode:
    - "EKSConfigMap"
  mapRoles:
    - roleARN: xxx
      username: xxx
      groups:
        - system:masters
  partition: "aws"

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: xxx-eksa
spec:
  tinkerbellIP: "10.255.xx.xx"

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: xxx-eksa-cp
spec:
  hardwareSelector:
    type: cp
  osFamily: ubuntu
  templateRef: {}
  users:
    - name: xxx
      sshAuthorizedKeys:
        - ssh-rsa AAAA...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: xxx-eksa-worker-default
spec:
  hardwareSelector:
    type: worker-default
  osFamily: ubuntu
  templateRef: {}
  users:
    - name: xxx
      sshAuthorizedKeys:
        - ssh-rsa AAAA...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: xxx-eksa-worker-gpu
spec:
  hardwareSelector:
    type: worker-gpu
  osFamily: ubuntu
  templateRef: {}
  users:
    - name: xxx
      sshAuthorizedKeys:
        - ssh-rsa AAAA...

---
```
