### ISSUE TITLE
Enable Volume Expansion for vSphere CSI

### ISSUE THREAD

**Issue by sleterrier** [aws/eks-anywhere#2908]
**What would you like to be added**:  `csi-resizer` sidecar container for `vsphere-csi-controller` pod, to allow for volume expansion.

According to [vsphere-csi-driver documentation](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-B1AAA825-3441-46D3-877C-A6580D2097D1.html):
> An external resizer sidecar container implements the logic of watching the Kubernetes API for PVC edits, issuing the ControllerExpandVolume RPC call against a CSI endpoint, and updating the PersistentVolume object to reflect the new size. This container is already deployed as part of the vsphere-csi-controller pod.

It is however not present on any of our EKS-A clusters:
```
kubectl get pods -l app=vsphere-csi-controller -n kube-system -o jsonpath='{.items[*].spec.containers[*].name}'
csi-attacher vsphere-csi-controller liveness-probe vsphere-syncer csi-provisioner
```

1. Could `csi-resizer` be added to the deployment managed by EKS-A by default?
2. Are there plans on allowing customization/management of `coredns`, `vsphere-csi-driver`, `kube-proxy` down the road?

**Environment**:
- EKS Anywhere Release: 0.10.0
- EKS Distro Release: v1.21.13-eks-3f70b89e

**Comment by sleterrier** [comment]
Here is what I have attempted so far to enable volume expansion:

- add `csi-resizer` container to `vpshere-csi-controller` pod:

```
kubectl edit deploy vsphere-csi-controller -n kube-system
```
```
     - args:
        - --v=4
        - --timeout=300s
        - --csi-address=$(ADDRESS)
        - --leader-election
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: quay.io/k8scsi/csi-resizer:v1.1.0
        imagePullPolicy: IfNotPresent
        name: csi-resizer
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
```

- Confirmed with:
```
kubectl get pods -l app=vsphere-csi-controller -n kube-system -o jsonpath='{.items[*].spec.containers[*].name}'
csi-resizer csi-attacher vsphere-csi-controller liveness-probe vsphere-syncer csi-provisioner
```

- Initially leading to:
```
controller.go:272] Error syncing PVC: marking pvc "monitoring/storage-loki-stack-0" as resizing failed: can't patch status of  PVC monitoring/storage-loki-stack-0 with persistentvolumeclaims "storage-loki-stack-0" is forbidden: User "system:serviceaccount:kube-system:vsphere-csi-controller" cannot patch resource "persistentvolumeclaims/status" in API group "" in the namespace "monitoring"
```

- So I added a rule to the `clusterrole`:
```
kubectl edit clusterrole vsphere-csi-controller-role
```
```
