### ISSUE TITLE
Flux fails to upgrade if flux-system kustomization is suspended

### ISSUE THREAD

**Issue by echel0n** [aws/eks-anywhere#3091]
**What happened**: 
attempted to perform a cluster upgrade but fails cause flux is unable to upgrade due to flux-system being suspended before flux bootstrap command executed

**What you expected to happen**:
flux-system kustomization to be unsuspended after flux-system secret is replaced and before flux bootstrap command is issued

**How to reproduce it (as minimally and precisely as possible)**:
attempt to upgrade a cluster that has a older version of flux then what the latest version is

**Anything else we need to know?**:
I was able to work around this by manually issuing the command `flux resume kustomization flux-system` before the flux bootstrap command was issued.

However, even after the cluster and flux upgrade finished successfully, flux version still reports the following old version
`Flux change diff        {"oldVersion ": "v0.29.4+e670ae4", "newVersion ": "v0.31.3+15d160e"}`

**Environment**:
- EKS Anywhere Release: 0.11.0
- EKS Distro Release: 1.22

**Comment by echel0n** [comment]
The cluster was originally created with EKS Anywhere v0.10.1 and was Flux-enabled, Flux kustomization is suspended automatically by the eksctl upgrade command it appears prior to it replacing the flux-system secret, also I did notice that when it fails to upgrade the cluster it does not resume the Flux kustomization.

Here is what I get when I run `eksctl anywhere upgrade plan cluster -f eksa-cluster.yaml`, keep in mind I have already upgraded the cluster, it seems to be improperly reporting versions as well.
```
Warning: VSphereDatacenterConfig configured in insecure mode
Checking new release availability...
NAME                 CURRENT VERSION   NEXT VERSION
EKS-A                v0.10.1+c59d2cc   v0.11.0+fcdfc21
Flux                 v0.29.4+e670ae4   v0.31.3+15d160e
cert-manager         v1.7.2+d4fa7e0    v1.8.2+543ab1d
cluster-api          v1.1.3+d32ac08    v1.2.0+06ada8a
kubeadm              v1.1.3+973f8a2    v1.2.0+a15cbd5
vsphere              v1.1.1+628bf01    v1.1.1+8aff43e
kubeadm              v1.1.3+9094d93    v1.2.0+dbcb744
etcdadm-bootstrap    v1.0.3+bfb8d15    v1.0.5+238c366
etcdadm-controller   v1.0.1+842bc86    v1.0.4+33fd30d
```

Here is what I get when I run `flux version`
```
flux: v0.31.5
helm-controller: v0.22.2-eks-a-14
kustomize-controller: v0.26.3-eks-a-14
notification-controller: v0.24.1-eks-a-14
source-controller: v0.25.9-eks-a-14
```

Here is what I get when I run `eksctl anywhere version`
`v0.11.0`

Below is the config I used prior to the upgrade:
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: prod
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-12
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 10.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: 192.168.3.10
    machineGroupRef:
      kind: VSphereMachineConfig
      name: prod-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: prod
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: prod-etcd
  gitOpsRef:
    kind: FluxConfig
    name: gitlab
  kubernetesVersion: "1.22"
  managementCluster:
    name: prod
  workerNodeGroupConfigurations:
  - count: 4
    machineGroupRef:
      kind: VSphereMachineConfig
      name: prod
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: prod
  namespace: default
spec:
  datacenter: Dark Systems Datacenter
  insecure: true
  network: /Dark Systems Datacenter/network/DSwitch-10GB-EKS
  server: vcenter.vsphere.darksystems.ca
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: prod-cp
  namespace: default
spec:
  datastore: /Dark Systems Datacenter/datastore/vsanDatastore
  diskGiB: 25
  folder: /Dark Systems Datacenter/vm/EKS Anywhere
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Dark Systems Datacenter/host/Cluster/Resources
  template: /Dark Systems Datacenter/vm/Templates/bottlerocket-vmware-k8s-1.22-x86_64-1.8.0-a6233c22
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: prod-etcd
  namespace: default
spec:
  datastore: /Dark Systems Datacenter/datastore/vsanDatastore
  diskGiB: 25
  folder: /Dark Systems Datacenter/vm/EKS Anywhere
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Dark Systems Datacenter/host/Cluster/Resources
  template: /Dark Systems Datacenter/vm/Templates/bottlerocket-vmware-k8s-1.22-x86_64-1.8.0-a6233c22
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: prod
  namespace: default
spec:
  datastore: /Dark Systems Datacenter/datastore/vsanDatastore
  diskGiB: 50
  folder: /Dark Systems Datacenter/vm/EKS Anywhere
  memoryMiB: 16384
  numCPUs: 16
  osFamily: bottlerocket
  resourcePool: /Dark Systems Datacenter/host/Cluster/Resources
  template: /Dark Systems Datacenter/vm/Templates/bottlerocket-vmware-k8s-1.22-x86_64-1.8.0-a6233c22
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: gitlab
  namespace: default
spec:
  branch: master
  clusterConfigPath: clusters/prod
  git:
    repositoryUrl: ssh://git@***.com/***/k8s-cluster.git
    sshKeyAlgorithm: ecdsa
  systemNamespace: flux-system

---
```
Below is the config I used to upgrade with:
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: prod
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-12
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 10.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: 192.168.3.10
    machineGroupRef:
      kind: VSphereMachineConfig
      name: prod-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: prod
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: prod-etcd
  gitOpsRef:
    kind: FluxConfig
    name: gitlab
  kubernetesVersion: "1.23"
  managementCluster:
    name: prod
  workerNodeGroupConfigurations:
  - count: 4
    machineGroupRef:
      kind: VSphereMachineConfig
      name: prod
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: prod
  namespace: default
spec:
  datacenter: Dark Systems Datacenter
  insecure: true
  network: /Dark Systems Datacenter/network/DSwitch-10GB-EKS
  server: vcenter.vsphere.darksystems.ca
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: prod-cp
  namespace: default
spec:
  datastore: /Dark Systems Datacenter/datastore/vsanDatastore
  diskGiB: 25
  folder: /Dark Systems Datacenter/vm/EKS Anywhere
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Dark Systems Datacenter/host/Cluster/Resources
  template: /Dark Systems Datacenter/vm/Templates/bottlerocket-vmware-k8s-1.23-x86_64-1.9.0-159e4ced
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: prod-etcd
  namespace: default
spec:
  datastore: /Dark Systems Datacenter/datastore/vsanDatastore
  diskGiB: 25
  folder: /Dark Systems Datacenter/vm/EKS Anywhere
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Dark Systems Datacenter/host/Cluster/Resources
  template: /Dark Systems Datacenter/vm/Templates/bottlerocket-vmware-k8s-1.23-x86_64-1.9.0-159e4ced
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: prod
  namespace: default
spec:
  datastore: /Dark Systems Datacenter/datastore/vsanDatastore
  diskGiB: 50
  folder: /Dark Systems Datacenter/vm/EKS Anywhere
  memoryMiB: 16384
  numCPUs: 16
  osFamily: bottlerocket
  resourcePool: /Dark Systems Datacenter/host/Cluster/Resources
  template: /Dark Systems Datacenter/vm/Templates/bottlerocket-vmware-k8s-1.23-x86_64-1.9.0-159e4ced
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: gitlab
  namespace: default
spec:
  branch: master
  clusterConfigPath: clusters/prod
  git:
    repositoryUrl: ssh://git@***.com/***/k8s-cluster.git
    sshKeyAlgorithm: ecdsa
  systemNamespace: flux-system

---
```
