### ISSUE TITLE
gitops FluxConfig does not support private git ssh urls

### ISSUE THREAD

**Issue by dashkan** [aws/eks-anywhere#3195]
**What happened**:
Updating a cluster with gitops FluxConfig does not work if using a private ssh url such as:
ssh://git@github.com:USER/repo.git

Get the following error:
Error: failed to display upgrade plan: unable to get cluster config from file: invalid cluster config: unable to parse repository url: parse "ssh://git@github.com:USER/repo.git": invalid port ":USER" after host

Please not that i replaced USER and repo name.

**What you expected to happen**:
Should work with any valid git ssh url

**How to reproduce it (as minimally and precisely as possible)**:

Add gitops section and reference section in cluster config:

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: management
spec:
  gitOpsRef:
    kind: FluxConfig
    name: gitops

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: gitops
spec:
    git:
      repositoryUrl: ssh://git@github.com:USER/repo.git
      sshKeyAlgorithm: ecdsa

```

**Anything else we need to know?**:
https://github.com/aws/eks-anywhere/blob/079ca2f5b838e81b9f7446519b0e895cc3205bf1/pkg/api/v1alpha1/fluxconfig.go#L3-L9

https://github.com/aws/eks-anywhere/blob/079ca2f5b838e81b9f7446519b0e895cc3205bf1/pkg/api/v1alpha1/fluxconfig.go#L77-L86

Looks like code uses net/url which tries to parse the USER portion of the git ssh url as a port.

**Environment**:
- EKS Anywhere Release: v0.11.1
- EKS Distro Release: 0.109.0
