### ISSUE TITLE
cilium not deployed

### ISSUE THREAD

**Issue by vincentmli** [aws/eks-anywhere#331]
**What happened**:

following https://anywhere.eks.amazonaws.com/docs/getting-started/local-environment/ to create local dev cluster, the cluster is up, but cilium is not deployed

dev-cluster.yaml
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: dev-cluster
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 10.0.0.0/8
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: dev-cluster
  externalEtcdConfiguration:
    count: 1
  kubernetesVersion: "1.21"
  workerNodeGroupConfigurations:
  - count: 1

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: dev-cluster
spec: {}
```
pod
```
# kubectl  get po -A
NAMESPACE                           NAME                                                              READY   STATUS              RESTARTS   AGE
capd-system                         capd-controller-manager-659dd5f8bc-vdrb5                          2/2     Running             0          26m
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-69889cb844-h9fpc        2/2     Running             0          26m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-6ddc66fb75-w5b9w    2/2     Running             0          26m
capi-system                         capi-controller-manager-db59f5789-k4qdr                           2/2     Running             0          26m
capi-webhook-system                 capi-controller-manager-64b8c548db-plfrs                          2/2     Running             0          26m
capi-webhook-system                 capi-kubeadm-bootstrap-controller-manager-68b8cc9759-clmtg        2/2     Running             0          26m
capi-webhook-system                 capi-kubeadm-control-plane-controller-manager-7dc88f767d-5zzjl    2/2     Running             0          26m
cert-manager                        cert-manager-5f6b885b4-r2mhb                                      1/1     Running             0          27m
cert-manager                        cert-manager-cainjector-bb6d9bcb5-tg8qg                           1/1     Running             0          27m
cert-manager                        cert-manager-webhook-56cbc8f5b8-lnjkx                             1/1     Running             0          27m
etcdadm-bootstrap-provider-system   etcdadm-bootstrap-provider-controller-manager-54476b7bf9-s5sv2    2/2     Running             0          26m
etcdadm-controller-system           etcdadm-controller-controller-manager-d5795556-xpzzh              2/2     Running             0          26m
kube-system                         coredns-7c68f85774-fq4jx                                          0/1     ContainerCreating   0          8m59s
kube-system                         coredns-7c68f85774-wv77r                                          0/1     ContainerCreating   0          9m14s
kube-system                         etcd-dev-cluster-eks-a-cluster-control-plane                      1/1     Running             0          27m
kube-system                         kindnet-j4m6z                                                     1/1     Running             0          27m
kube-system                         kube-apiserver-dev-cluster-eks-a-cluster-control-plane            1/1     Running             0          27m
kube-system                         kube-controller-manager-dev-cluster-eks-a-cluster-control-plane   1/1     Running             0          27m
kube-system                         kube-proxy-s545n                                                  1/1     Running             0          27m
kube-system                         kube-scheduler-dev-cluster-eks-a-cluster-control-plane            1/1     Running             0          27m
local-path-storage                  local-path-provisioner-666bfc797f-8wpv8                           1/1     Running             0          27m
```

**What you expected to happen**:

expect cilium to be deployed

**How to reproduce it (as minimally and precisely as possible)**:

follow steps in https://anywhere.eks.amazonaws.com/docs/getting-started/local-environment/

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
v0.5.0

- EKS Distro Release:
