### ISSUE TITLE
eksctl plan cluster upgrade command reports incorrect current versions

### ISSUE THREAD

**Issue by echel0n** [aws/eks-anywhere#3318]
**What happened**:
when running `eksctl anywhere upgrade plan cluster -f eksa-cluster.yaml` the returned current versions are incorrect

**What you expected to happen**:
`eksctl anywhere upgrade plan cluster -f eksa-cluster.yaml` should report correct current and next versions

**How to reproduce it (as minimally and precisely as possible)**:
run `eksctl anywhere upgrade plan cluster -f eksa-cluster.yaml` twice and you will see the 2nd run will report the same old versions under `current`

**Anything else we need to know?**:
```
$ eksctl anywhere upgrade plan cluster -f eksa-cluster.yaml
Warning: VSphereDatacenterConfig configured in insecure mode
Checking new release availability...
NAME                 CURRENT VERSION   NEXT VERSION
EKS-A                v0.10.1+c59d2cc   v0.11.2+cd46e1d
Flux                 v0.29.4+e670ae4   v0.31.3+5738265
cert-manager         v1.7.2+d4fa7e0    v1.8.2+543ab1d
cluster-api          v1.1.3+d32ac08    v1.2.0+172e2ab
kubeadm              v1.1.3+973f8a2    v1.2.0+525dbd6
vsphere              v1.1.1+628bf01    v1.1.1+2fc04d0
kubeadm              v1.1.3+9094d93    v1.2.0+115b0d5
etcdadm-bootstrap    v1.0.3+bfb8d15    v1.0.5+77e4d45
etcdadm-controller   v1.0.1+842bc86    v1.0.4+05b4294
cilium               v1.10.11-eksa.2   v1.10.14-eksa.1
$ flux version
flux: v0.31.5
helm-controller: v0.22.2-eks-a-16
kustomize-controller: v0.26.3-eks-a-16
notification-controller: v0.24.1-eks-a-16
source-controller: v0.25.9-eks-a-16
```
**Environment**:
- EKS Anywhere Release: 0.11.2
- EKS Distro Release: 1.23

**Comment by jonahjon** [comment]
Thanks for raising this issue, will check in with the CLI team on this.

**Comment by vivek-koppuru** [comment]
Hi @echel0n, when you are referring to the current versions, are you referring to the flux binary that is installed on your local machine? We use different dependencies to install flux, packaged within a docker container, so the versions that we use may not match the ones that are located on your local machine.

**Comment by echel0n** [comment]
@vivek-koppuru I have done the upgrade command several times and those values under the `current` column never change and remain the same,

Here is the flux version from gotk-components.yaml
```
---
# This manifest was generated by flux. DO NOT EDIT.
# Flux Version: v0.31.3
# Components: source-controller,kustomize-controller,helm-controller,notification-controller
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.31.3
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: flux-system
```

**Comment by vivek-koppuru** [comment]
Oh I see what you are saying, after running an upgrade it still shows the wrong current versions. Let me do some investigation on that.

**Comment by vivek-koppuru** [comment]
@echel0n A couple of things I might need from you:

1. Can you run `kubectl get cluster <cluster-name> -o yaml` and see what name is listed under the `bundlesRef`?
2. Then, can you run 'kubectl get bundles <bundles-name> -o yaml` and see what version is listed under `flux`?
3. Do you have GitOps enabled? If so, is there a bundles ref specified in the repository that might be overriding what is in the cluster? I am wondering if this is a bug that you are facing which I can try to reproduce as well as currently without GitOps enabled it seems like I am not able to repro it on my end.

Let's see what this information gets us to see where the issue might be.

**Comment by echel0n** [comment]
kubectl get cluster prod -o yaml
```
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-12
```
```
$ kubectl get bundles bundles-12 -o yaml
Error from server (NotFound): bundles.anywhere.eks.amazonaws.com "bundles-12" not found
```

bundlesRef in our git repo is same as what is in our cluster, `bundles-12`

**Comment by echel0n** [comment]
Any chance you would be able to provide me the yaml for what bundles-12 should contain so I can re-create it, if that is the issue here as it appears to be missing.

**Comment by vivek-koppuru** [comment]
I think it is under the `eksa-system` namespace, you should already have it

**Comment by echel0n** [comment]
Well this is interesting, I see other bundles under that namespace, so why am I still on bundles-12 when bundles-16 is the latest?

```
$ kubectl get bundles -n eksa-system
NAME         AGE
bundles-12   37d
bundles-14   22d
bundles-16   5d17h
```

bundles-12
```
    flux:
      helmController:
        arch:
        - amd64
        description: Container image for helm-controller image
        imageDigest: sha256:4b7e5046cc1e3ff18278b179ded1d6adc5172f33827162f5cc7bcf3608746871
        name: helm-controller
        os: linux
        uri: public.ecr.aws/eks-anywhere/fluxcd/helm-controller:v0.20.1-eks-a-12
      kustomizeController:
        arch:
        - amd64
        description: Container image for kustomize-controller image
        imageDigest: sha256:136d4866cebcd3f9d2a4d357cea0650511f6dc74c706266986fd2a814a17bf20
        name: kustomize-controller
        os: linux
        uri: public.ecr.aws/eks-anywhere/fluxcd/kustomize-controller:v0.24.3-eks-a-12
      notificationController:
        arch:
        - amd64
        description: Container image for notification-controller image
        imageDigest: sha256:30c7ec3d1f181225b8e3ebd725bc0018b39b95af35f5dc5f351a0aaf233cc9c5
        name: notification-controller
        os: linux
        uri: public.ecr.aws/eks-anywhere/fluxcd/notification-controller:v0.23.4-eks-a-12
      sourceController:
        arch:
        - amd64
        description: Container image for source-controller image
        imageDigest: sha256:c13491f03c03bb4805ce98cb62c6e9e28654a83f7f3b1321be0df0581d80009f
        name: source-controller
        os: linux
        uri: public.ecr.aws/eks-anywhere/fluxcd/source-controller:v0.24.2-eks-a-12
      version: v0.29.4+e670ae4
```

bundles-16
```
    flux:
      helmController:
        arch:
        - amd64
        - arm64
        description: Container image for helm-controller image
        imageDigest: sha256:623fc35cb4cb66e01030646e4223ad1b1963d3197ece0617c12d3006261b5e25
        name: helm-controller
        os: linux
        uri: public.ecr.aws/eks-anywhere/fluxcd/helm-controller:v0.22.2-eks-a-16
      kustomizeController:
        arch:
        - amd64
        - arm64
        description: Container image for kustomize-controller image
        imageDigest: sha256:c2e45dc2879bb1d5e9a001beff9e87953aae9a357d4309db204d87774fc3cc8b
        name: kustomize-controller
        os: linux
        uri: public.ecr.aws/eks-anywhere/fluxcd/kustomize-controller:v0.26.3-eks-a-16
      notificationController:
        arch:
        - amd64
        - arm64
        description: Container image for notification-controller image
        imageDigest: sha256:72fde2cd2a8f0df7cee37650300e87a9248b8d93686cffbbf61a8449aa274711
        name: notification-controller
        os: linux
        uri: public.ecr.aws/eks-anywhere/fluxcd/notification-controller:v0.24.1-eks-a-16
      sourceController:
        arch:
        - amd64
        - arm64
        description: Container image for source-controller image
        imageDigest: sha256:788a2d2580869c7ec7ba6cf5d8dbf3938c5892ce13ea16a052ea2759a5e4f031
        name: source-controller
        os: linux
        uri: public.ecr.aws/eks-anywhere/fluxcd/source-controller:v0.25.9-eks-a-16
      version: v0.31.3+5738265
```

**Comment by vivek-koppuru** [comment]
Right, which is why I am wondering whether you have GitOps enabled or not. I am wondering if something is overriding the values.

**Comment by echel0n** [comment]
I do have GitOps enabled, but I perform the cluster upgrade from cli, I've reviewed commit history specifically for the eksa-cluster.yaml and the bundles-12 ref has never been updated or changed for any commits marked "Update commit of cluster configuration; generated by EKS-A CLI", so it appears `eksctl` is not updating the bundles ref at all

**Comment by vivek-koppuru** [comment]
What does the yaml spec look like in the repo?

**Comment by echel0n** [comment]
Below is contents from the cluster yaml in the repo, it does include a bundleRef as well
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: prod
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-12
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 10.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: 192.168.3.10
    machineGroupRef:
      kind: VSphereMachineConfig
      name: prod-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: prod
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: prod-etcd
  gitOpsRef:
    kind: FluxConfig
    name: gitlab
  identityProviderRefs:
  - kind: OIDCConfig
    name: prod
  kubernetesVersion: "1.23"
  managementCluster:
    name: prod
  workerNodeGroupConfigurations:
  - count: 4
    machineGroupRef:
      kind: VSphereMachineConfig
      name: prod
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: prod
  namespace: default
spec:
  datacenter: Dark Systems Datacenter
  insecure: true
  network: /Dark Systems Datacenter/network/DSwitch-10GB-EKS
  server: removed
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: prod-cp
  namespace: default
spec:
  datastore: /Dark Systems Datacenter/datastore/vsanDatastore
  diskGiB: 25
  folder: /Dark Systems Datacenter/vm/EKS Anywhere
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Dark Systems Datacenter/host/Cluster/Resources
  template: /Dark Systems Datacenter/vm/Templates/bottlerocket-vmware-k8s-1.23-x86_64-1.9.0-159e4ced
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: prod-etcd
  namespace: default
spec:
  datastore: /Dark Systems Datacenter/datastore/vsanDatastore
  diskGiB: 25
  folder: /Dark Systems Datacenter/vm/EKS Anywhere
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Dark Systems Datacenter/host/Cluster/Resources
  template: /Dark Systems Datacenter/vm/Templates/bottlerocket-vmware-k8s-1.23-x86_64-1.9.0-159e4ced
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: prod
  namespace: default
spec:
  datastore: /Dark Systems Datacenter/datastore/vsanDatastore
  diskGiB: 50
  folder: /Dark Systems Datacenter/vm/EKS Anywhere
  memoryMiB: 24576
  numCPUs: 16
  osFamily: bottlerocket
  resourcePool: /Dark Systems Datacenter/host/Cluster/Resources
  template: /Dark Systems Datacenter/vm/Templates/bottlerocket-vmware-k8s-1.23-x86_64-1.9.0-159e4ced
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: gitlab
  namespace: default
spec:
  branch: master
  clusterConfigPath: clusters/prod
  git:
    repositoryUrl: removed
    sshKeyAlgorithm: ecdsa
  systemNamespace: flux-system

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: OIDCConfig
metadata:
  name: prod
  namespace: default
spec:
  clientId: removed
  groupsClaim: groups
  issuerUrl: removed
  requiredClaims:
  - {}
  usernameClaim: email

---
```

**Comment by vivek-koppuru** [comment]
Yea that is what I am suspecting the issue is. If you update the gitops spec to use the latest bundle ref, I think it should work as expected, and the CLI upgrade plan should reflect the right values. However, I am suspecting that this is a bug because this file should be updated as part of upgrade, which maybe we aren't doing in some cases.

**Comment by echel0n** [comment]
ok, I can confirm that updating the bundleRef to latest available bundle resolved the issue for it displaying up to date components, however, I do believe there still is a bug that prevents this from being updated so request we leave this ticket open till that is sorted out, thanks!

```
$ eksctl anywhere upgrade plan cluster -f eksa-cluster.yaml
Warning: VSphereDatacenterConfig configured in insecure mode
Checking new release availability...
All the components are up to date with the latest versions
```

**Comment by vivek-koppuru** [comment]
Yes this will be something that we will prioritize. Thank you for raising this issue!

**Comment by echel0n** [comment]
just to confirm, having the bundleRef in my cluster yaml file that I use to upgrade the cluster from cli, that wouldn't cause issues right ?

**Comment by vivek-koppuru** [comment]
It shouldn't cause issues as for the CLI we try to retrieve the latest bundle available to that CLI version.

**Comment by vivek-koppuru** [comment]
Hey @echel0n, I tried to run this locally but I am not able to repro the error. I run create cluster with a `v0.10.1` binary, then ran upgrade plan with `v0.11.2` and saw the similar versions to you. Then ran upgrade and it updated the file in github for me, and I see the proper output. Did you see any errors from the first time you ran upgrade when you noticed nothing happening? I will try running with vsphere next.

Before upgrade:
```
[ec2-user@ip-172-31-8-141 ~]$ eksctl anywhere upgrade plan cluster -f docker.yaml
Checking Github Access Token permissions
✅ Github personal access token has the required repo permissions
Checking new release availability...
NAME                 CURRENT VERSION   NEXT VERSION
EKS-A                v0.10.2+df9011f   v0.11.2+cd46e1d
Flux                 v0.29.4+e7f77a9   v0.31.3+5738265
cert-manager         v1.7.2+322f4aa    v1.8.2+543ab1d
cluster-api          v1.1.3+552494c    v1.2.0+172e2ab
kubeadm              v1.1.3+a8e46f5    v1.2.0+525dbd6
docker               v1.1.3+c7d24d7    v1.2.0+12e373a
kubeadm              v1.1.3+6dc25b3    v1.2.0+115b0d5
etcdadm-bootstrap    v1.0.3+db15860    v1.0.5+77e4d45
etcdadm-controller   v1.0.1+a367e7e    v1.0.4+05b4294
cilium               v1.10.11-eksa.2   v1.10.14-eksa.1
```

After upgrade:
```
[ec2-user@ip-172-31-8-141 ~]$ eksctl anywhere upgrade plan cluster -f docker.yaml
Checking Github Access Token permissions
✅ Github personal access token has the required repo permissions
Checking new release availability...
All the components are up to date with the latest versions
```

yaml file in github after upgrade:
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: docker-test
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-16
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: docker-test
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: GitOpsConfig
    name: docker-test
  kubernetesVersion: "1.22"
  managementCluster:
    name: docker-test
  workerNodeGroupConfigurations:
  - count: 1
    name: md-0
```
