### ISSUE TITLE
Add validations for tinkerbell `upgrade` to make unsupported fields immutable

### ISSUE THREAD

**Issue by pokearu** [aws/eks-anywhere#3412]
## Description
Currently we support k8s version upgrade and scale up/down for `upgrade` with Tinkerbell provider.
We require validations to make the unsupported objects from the clusterconfig to be immutable.

```yaml
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellTemplateConfig
...
```

This issue also helps prevent #3341
