### ISSUE TITLE
KCP rolling upgrade occurs when applied the same cluster manifest after cluster creation

### ISSUE THREAD

**Issue by wongni** [aws/eks-anywhere#3448]
**What happened**:

KCP rolling upgrade occurs when applied the same cluster manifest after cluster creation

**What you expected to happen**:

No rolling upgrade to occur when applied the same cluster manifest that is used when creating a cluster

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster using the attached cluster manifest (Note that it already has bundlesRef )
2. After successful creation, apply the same cluster manifest to the cluster using kubectl apply -f
3. The KCP is rolling-upgraded
4. The MD is not upgraded

**Anything else we need to know?**:

I compared the kcp description before and after applying and I found the sshAuthorizedKeys are different. 

Before

```
      users:
      - name: user
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIITl4xxtEDke17+O6HJIKU7nN/smK51FN/TqXX
```

After

```
     users:
      - name: user
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIITl4xxtEDke17+O6HJIKU7nN/smK51FN/TqXX
          test@email.com
```

**Environment**:
- EKS Anywhere Release: 0.11.3
- EKS Distro Release:
