### ISSUE TITLE
failed setting default values for vsphere machine configs: failed importing template into library

### ISSUE THREAD

**Issue by antoine-faisandier** [aws/eks-anywhere#3518]
**What happened**:
2022-09-30T15:33:49.479+1100	V0	Creating template. This might take a while.

2022-09-30T15:33:49.479+1100	V6	Executing command	{"cmd": "/usr/bin/docker exec -i -e GOVC_PASSWORD=***** -e GOVC_URL=******** -e GOVC_INSECURE=true -e GOVC_DATACENTER=*** -e GOVC_USERNAME=***** eksa_1664512421858191080 govc library.info -json eks-a-templates/bottlerocket-v1.23.9-kubernetes-1-23-eks-5-amd64-9fd2167"}

2022-09-30T15:33:49.642+1100	V2	Importing template from ova url	{"ova": "https://anywhere-assets.eks.amazonaws.com/releases/bundles/17/artifacts/ova/1-23/bottlerocket-v1.23.9-eks-d-1-23-5-eks-a-17-amd64.ova"}

2022-09-30T15:33:49.642+1100	V4	Importing template	{"ova": "https://anywhere-assets.eks.amazonaws.com/releases/bundles/17/artifacts/ova/1-23/bottlerocket-v1.23.9-eks-d-1-23-5-eks-a-17-amd64.ova", "templateName": "bottlerocket-v1.23.9-kubernetes-1-23-eks-5-amd64-9fd2167"}

2022-09-30T15:33:49.642+1100	V6	Executing command	{"cmd": "/usr/bin/docker exec -i -e GOVC_INSECURE=true -e GOVC_DATACENTER=**** -e GOVC_USERNAME=***** -e GOVC_PASSWORD=***** -e GOVC_URL=***** eksa_1664512421858191080 govc library.import -k -pull -n bottlerocket-v1.23.9-kubernetes-1-23-eks-5-amd64-9fd2167 eks-a-templates https://anywhere-assets.eks.amazonaws.com/releases/bundles/17/artifacts/ova/1-23/bottlerocket-v1.23.9-eks-d-1-23-5-eks-a-17-amd64.ova"}

2022-09-30T15:33:51.502+1100	V9	docker	{"stderr": "govc: POST https://******/rest/com/vmware/content/library/item/updatesession/file/id:?~action=add: 404 Not Found\n"}

2022-09-30T15:33:51.502+1100	V0	❌ Validation failed	{"validation": "vsphere Provider setup is valid", "error": "failed setting default values for vsphere machine configs: failed importing template into library: importing template: govc: POST https://*******/rest/com/vmware/content/library/item/updatesession/file/id:?~action=add: 404 Not Found\n", "remediation": ""}

**How to reproduce it (as minimally and precisely as possible)**:
eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml -v 9

**Anything else we need to know?**:

```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "*********"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: mgmt
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-etcd
  kubernetesVersion: "1.23"
  managementCluster:
    name: mgmt
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: mgmt
spec:
  datacenter: "****"
  insecure: true
  network: "*******"
  server: "******"
  thumbprint: "*******"

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-cp
spec:
  datastore: "********"
  diskGiB: 25
  folder: "EKS Anywhere"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "Eks_anywhere"
  template: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt
spec:
  datastore: "********"
  diskGiB: 25
  folder: "EKS Anywhere"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "Eks_anywhere"
  template: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""
---
apiVersion:` anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-etcd
spec:
  datastore: "********"
  diskGiB: 25
  folder: "EKS Anywhere"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "Eks_anywhere"
  template: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""
---
```

**Environment**:
eksctl version
0.111.0-dev+9a99e9218.2022-09-09T18:36:17Z

eksctl anywhere version
v0.11.3

VMware vCenter Server 7.0.3 

govc 0.29.0
