### ISSUE TITLE
CNI not initialized and EKS-A Cluster not ready (vSphere environment)

### ISSUE THREAD

**Issue by varanto** [aws/eks-anywhere#3587]
**What happened**:
Tried to create a new cluster on VMWare environment following the guide step by step with bottlerocket template. The command used is the following:

eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml -v9

The procedure stops with the following output:

...    V5      Error happened during retry     {"error": "nodes are not ready yet", "retries": 809}
...    V5      Sleeping before next retry      {"time": "2s"}

At the end of the timeout, VMs were correctly created in vSphere, but the K8s cluster was not ready (all the nodes were in the NotReady state) and no CNI was installed. 

For each node we see the following status condition:

KubeletNotReady:  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized

**What you expected to happen**:
The cluster should be correctly created with the CNI correctly initialized.

**How to reproduce it (as minimally and precisely as possible)**:
vSphere Environment with 2 Datacenter
vSphere Version:	7.0.3  Build:	19480866

Operating system used for VM creation
Kernel Version:                            5.10.130
OS Image:                                      Bottlerocket OS 1.9.2 (vmware-k8s-1.22)
Operating System:                      linux
Architecture:                                amd64
Container Runtime Version:     containerd://1.6.6+bottlerocket
Kubelet Version:                          v1.22.10-eks-7dc61e8
Kube-Proxy Version:                   v1.22.10-eks-7dc61e8

Execute the command: eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml -v9
(the eksa-mgmt-cluster.yaml is in the following section)

**Anything else we need to know?**:
YAML FILE

```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
   name: mgmt
spec:
   clusterNetwork:
      cniConfig:
         cilium: {}
      pods:
         cidrBlocks:
            - 192.168.0.0/16
      services:
         cidrBlocks:
            - 10.96.0.0/12
   controlPlaneConfiguration:
      count: 1
      endpoint:
         host: "xxx.xxx.xxx.xxx"
      machineGroupRef:
        kind: VSphereMachineConfig
        name: my-cluster-machines
   datacenterRef:
      kind: VSphereDatacenterConfig
      name: my-cluster-datacenter
   externalEtcdConfiguration:
     count: 1
     machineGroupRef:
        kind: VSphereMachineConfig
        name: my-cluster-machines
   kubernetesVersion: "1.22"
   workerNodeGroupConfigurations:
   - count: 1
     machineGroupRef:
       kind: VSphereMachineConfig
       name: my-cluster-machines
     name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
   name: my-cluster-datacenter
spec:
  datacenter: "L22Datacenter"
  insecure: true
  network: "XXXXXXXX"
  server: "xxx.xxx.xxx.xxx"
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
   name: my-cluster-machines
spec:
  datastore: "Datastore iSCSI-1"
  template: "/L22Datacenter/vm/Edgecloud folder/bottlerocket-vmware-k8s-1.22-x86_64-1.9.2"
  diskGiB: 30
  folder: "Edgecloud folder"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/L22Datacenter/host/Edgecloud Cluster/Resources"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ""
---
```

Detailed output of the eksctl anywhere create command:

2022-09-28T12:35:15.732+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 kubectl get machines -o json --kubeconfig mgmt/generated/mgmt.kind.kubeconfig --selector=cluster.x-k8s.io/cluster-name=mgmt --namespace eksa-system"}
2022-09-28T12:35:15.973+0200    V4      Nodes are not ready yet {"total": 2, "ready": 0, "cluster name": "mgmt"}
2022-09-28T12:35:15.973+0200    V5      Error happened during retry     {"error": "nodes are not ready yet", "retries": 807}
2022-09-28T12:35:15.973+0200    V5      Timeout reached. Returning error        {"retries": 807, "duration": "29m58.087535507s", "error": "nodes are not ready yet"}
2022-09-28T12:35:15.973+0200    V4      Task finished   {"task_name": "workload-cluster-init", "duration": "34m5.918191963s"}
2022-09-28T12:35:15.973+0200    V4      ----------------------------------
2022-09-28T12:35:15.973+0200    V4      Task start      {"task_name": "collect-cluster-diagnostics"}
2022-09-28T12:35:15.973+0200    V0      collecting cluster diagnostics
2022-09-28T12:35:15.973+0200    V0      collecting management cluster diagnostics
2022-09-28T12:35:15.985+0200    V3      bundle config written   {"path": "mgmt/generated/bootstrap-cluster-2022-09-28T12:35:15+02:00-bundle.yaml"}
2022-09-28T12:35:15.985+0200    V1      creating temporary namespace for diagnostic collector   {"namespace": "eksa-diagnostics"}
2022-09-28T12:35:15.985+0200    V5      Retrier:        {"timeout": "2562047h47m16.854775807s", "backoffFactor": null}
2022-09-28T12:35:15.985+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 kubectl create namespace eksa-diagnostics --kubeconfig mgmt/generated/mgmt.kind.kubeconfig"}
2022-09-28T12:35:16.206+0200    V5      Retry execution successful      {"retries": 1, "duration": "220.829695ms"}
2022-09-28T12:35:16.206+0200    V1      creating temporary ClusterRole and RoleBinding for diagnostic collector
2022-09-28T12:35:16.206+0200    V5      Retrier:        {"timeout": "2562047h47m16.854775807s", "backoffFactor": null}
2022-09-28T12:35:16.206+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 kubectl apply -f - --kubeconfig mgmt/generated/mgmt.kind.kubeconfig"}
2022-09-28T12:35:16.653+0200    V5      Retry execution successful      {"retries": 1, "duration": "446.934383ms"}
2022-09-28T12:35:16.653+0200    V0      ⏳ Collecting support bundle from cluster, this can take a while        {"cluster": "bootstrap-cluster", "bundle": "mgmt/generated/bootstrap-cluster-2022-09-28T12:35:15+02:00-bundle.yaml", "since": "2022-09-28T09:35:15.985+0200", "kubeconfig": "mgmt/generated/mgmt.kind.kubeconfig"}
2022-09-28T12:35:16.653+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 support-bundle mgmt/generated/bootstrap-cluster-2022-09-28T12:35:15+02:00-bundle.yaml --kubeconfig mgmt/generated/mgmt.kind.kubeconfig --interactive=false --since-time 2022-09-28T09:35:15.985592887+02:00"}
2022-09-28T12:36:33.371+0200    V0      Support bundle archive created  {"path": "support-bundle-2022-09-28T10_35_16.tar.gz"}
2022-09-28T12:36:33.371+0200    V0      Analyzing support bundle        {"bundle": "mgmt/generated/bootstrap-cluster-2022-09-28T12:35:15+02:00-bundle.yaml", "archive": "support-bundle-2022-09-28T10_35_16.tar.gz"}
2022-09-28T12:36:33.371+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 support-bundle analyze mgmt/generated/bootstrap-cluster-2022-09-28T12:35:15+02:00-bundle.yaml --bundle support-bundle-2022-09-28T10_35_16.tar.gz --output json"}
2022-09-28T12:36:33.939+0200    V0      Analysis output generated       {"path": "mgmt/generated/bootstrap-cluster-2022-09-28T12:36:33+02:00-analysis.yaml"}
2022-09-28T12:36:33.939+0200    V1      cleaning up temporary roles for diagnostic collectors
2022-09-28T12:36:33.939+0200    V5      Retrier:        {"timeout": "2562047h47m16.854775807s", "backoffFactor": null}
2022-09-28T12:36:33.939+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 kubectl delete -f - --kubeconfig mgmt/generated/mgmt.kind.kubeconfig"}
2022-09-28T12:36:34.150+0200    V5      Retry execution successful      {"retries": 1, "duration": "210.804437ms"}
2022-09-28T12:36:34.150+0200    V1      cleaning up temporary namespace  for diagnostic collectors      {"namespace": "eksa-diagnostics"}
2022-09-28T12:36:34.150+0200    V5      Retrier:        {"timeout": "2562047h47m16.854775807s", "backoffFactor": null}
2022-09-28T12:36:34.150+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 kubectl delete namespace eksa-diagnostics --kubeconfig mgmt/generated/mgmt.kind.kubeconfig"}
2022-09-28T12:36:39.650+0200    V5      Retry execution successful      {"retries": 1, "duration": "5.500767446s"}
2022-09-28T12:36:39.650+0200    V0      collecting workload cluster diagnostics
2022-09-28T12:36:39.658+0200    V3      bundle config written   {"path": "mgmt/generated/mgmt-2022-09-28T12:36:39+02:00-bundle.yaml"}
2022-09-28T12:36:39.658+0200    V1      creating temporary namespace for diagnostic collector   {"namespace": "eksa-diagnostics"}
2022-09-28T12:36:39.658+0200    V5      Retrier:        {"timeout": "2562047h47m16.854775807s", "backoffFactor": null}
2022-09-28T12:36:39.658+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 kubectl create namespace eksa-diagnostics --kubeconfig mgmt/mgmt-eks-a-cluster.kubeconfig"}
2022-09-28T12:36:39.872+0200    V5      Retry execution successful      {"retries": 1, "duration": "213.678727ms"}
2022-09-28T12:36:39.872+0200    V1      creating temporary ClusterRole and RoleBinding for diagnostic collector
2022-09-28T12:36:39.872+0200    V5      Retrier:        {"timeout": "2562047h47m16.854775807s", "backoffFactor": null}
2022-09-28T12:36:39.872+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 kubectl apply -f - --kubeconfig mgmt/mgmt-eks-a-cluster.kubeconfig"}
2022-09-28T12:36:41.138+0200    V5      Retry execution successful      {"retries": 1, "duration": "1.265961086s"}
2022-09-28T12:36:41.138+0200    V0      ⏳ Collecting support bundle from cluster, this can take a while        {"cluster": "mgmt", "bundle": "mgmt/generated/mgmt-2022-09-28T12:36:39+02:00-bundle.yaml", "since": "2022-09-28T09:36:39.658+0200", "kubeconfig": "mgmt/mgmt-eks-a-cluster.kubeconfig"}
2022-09-28T12:36:41.138+0200    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1664359052791997161 support-bundle mgmt/generated/mgmt-2022-09-28T12:36:39+02:00-bundle.yaml --kubeconfig mgmt/mgmt-eks-a-cluster.kubeconfig --interactive=false --since-time 2022-09-28T09:36:39.658181274+02:00"}
^C2022-09-28T15:10:52.545+0200  V0      Warning: Terminating this operation may leave the cluster in an irrecoverable state

**Environment**:
- EKSCTL Release: 0.112.0
- EKS Anywhere Release: v0.11.3
- EKS Distro Release: v1.22.10-eks-7dc61e8
