### ISSUE TITLE
Document implicit dynamic label value supported by CloudStack cluster

### ISSUE THREAD

**Issue by wanyufe** [aws/eks-anywhere#3735]
**What happened**:
To support labeling node with failuredomain info, Cloudstack provider supports a placehold string `ds.meta_data.failuredomain` and this string will be replaced with failuredomain name where the node is located.

To use it, eksa customer needs to add a label section under `controlPlaneConfiguration` or `workerNodeGroupConfiguration`:
for example: 
```
controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 192.168.1.141:6443
    machineGroupRef:
      kind: CloudStackMachineConfig
      name: wanyufe-cp
    labels:
      cluster.x-k8s.io/failure-domain: ds.meta_data.failuredomain
```

**What you expected to happen**:
This needs to be documented in eksa doc.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:
