### ISSUE TITLE
Kubernetes network policy gets ignored

### ISSUE THREAD

**Issue by Cajga** [aws/eks-anywhere#4406]
**What happened**:
I am applying network policy to allow collecting flux metrics through nodeports but seems EKS-A cilium ignores it. Here is my network policy:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-scraping-through-nodeport
  namespace: flux-system
spec:
  podSelector: {}
  ingress:
    - from:
        - ipBlock:
            cidr: 172.27.48.0/24
      ports:
        - port: 8080
```

Even if I apply it, I get the following drop message through `cilium monitor --type drop`:
_xx drop (Policy denied) flow 0xac2e1c00 to endpoint 3065, , identity world->53020: 172.27.48.111:25644 -> 100.80.1.171:8080 tcp SYN_

BUT if I change the **`cidr` to `0.0.0.0/0` then the connection works as it should**.

Why does 0.0.0.0/0 works while the proper cidr does not?

**What you expected to happen**:
Proper/stricter cidr works as well.

**How to reproduce it (as minimally and precisely as possible)**:
* Install EKS-A with default CNI settings
* Create a nodeport service:
```
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  type: NodePort
  selector:
    app: helm-controller
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32766
      name: prom-nodeport
```
* Apply a network policy to allow it using your remote host cidr (see above the example network policy)
* Try to hit the nodeport with curl

**Anything else we need to know?**:
I guess it could be helpful: I used the following commands to start the monitor in the proper cilium pod:
```
export PODNAME=helm-controller-5b795444b4-b74c2
export PODNAMESPACE=flux-system
kubectl -n kube-system exec -ti $(kubectl get pods -n kube-system -o wide |grep cilium|grep $(kubectl get pod $PODNAME -n $PODNAMESPACE -o jsonpath='{.spec.nodeName}')|grep -v operator|awk '{print $1}') -- cilium monitor --type drop
```

**Environment**:
- EKS Anywhere Release: v0.12.2
- EKS Distro Release: 1.24

**Comment by g-gaston** [comment]
Thanks for the report @Cajga! We will try to reproduce it on our end.

**Comment by g-gaston** [comment]
Hey @Cajga could you provide your cluster config yaml?
Specially the cilium config part

**Comment by Cajga** [comment]
Hi @g-gaston,

Sure, here is the `kind: Cluster` of our config:
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: eks-a-bm-poc
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 100.80.0.0/16
    services:
      cidrBlocks:
      - 100.81.0.0/16
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: "192.168.35.68"
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eks-a-bm-poc-cp
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eks-a-bm-poc
  kubernetesVersion: "1.24"
  managementCluster:
    name: eks-a-bm-poc
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eks-a-bm-worker01
    name: worker01
  identityProviderRefs:
  - kind: OIDCConfig
    name: eks-anywhere-azuread
  gitOpsRef:
    name: kubernetes-infra-addons
    kind: FluxConfig
```
