### ISSUE TITLE
I want to change the storagePolicyName used in the default StorageClass deployed in VMware

### ISSUE THREAD

**Issue by raykrueger** [aws/eks-anywhere#4502]
**What would you like to be added**:
I want to change the storagePolicyName used in the [default StorageClass](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/defaultStorageClass.yaml) deployed in VMware.

**Why is this needed**:
The default storage class deployed to VMware clusters is hardcoded to use the default storage policy in VMware. Many administrators disable that policy and deploy custom policies in their VMware environments.

Note that there is an issue mentioning this #1353 currently. However, that issue refers to the VSphereMachineConfig, which has nothing to do with Kubernetes Storage Policies.

**Comment by raykrueger** [comment]
(I am copying my design suggestion over from the previous issue to this one)

I think it might be a bit unclear if we were defaulting to a storgePolicyName defined on nodes, when nodes really have nothing to do with the Kubernetes StorageClasses.

I would rather see us be explicit and define a StorageClass in the cluster.yaml at creation time, essentially overriding the [default specified here](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/defaultStorageClass.yaml)

For example, in my cluster config (cut for brevity)...
```
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: ray
spec:
  ...
  defaultStorageClassRef:
  - kind: StorageClass
    name: standard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
    storagePolicyName: "My Storage Policy"

---
```
