### ISSUE TITLE
We need the ability to specify annotations in the spec of a VSphereMachineConfig to be propagated to VSphereMachineTemplates

### ISSUE THREAD

**Issue by nickperry** [aws/eks-anywhere#4536]
**What would you like to be added**:

We need the ability to specify annotations in the spec of a VSphereMachineConfig to be propagated to the spec.template.metadata.annotations of the resultant VSphereMachineTemplate.

**Why is this needed**:

We cannot use DHCP in our environment and instead use Infoblox IPAM in conjunction with a controller in our management clusters. This IPAM controller acts upon annotations set in the metadata of VSphereMachine resources.

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
spec:
  template:
    metadata:
      annotations:
        ipam.schiff.telekom.de/NetworkName: #@ "{}".format(data.values.VSPHERE_NETWORK_DMZ)
        ipam.schiff.telekom.de/Subnet: #@ "{}".format(data.values.INFOBLOX_SUBNET_DMZ)
        ipam.schiff.telekom.de/InfobloxNetworkView: default
        ipam.schiff.telekom.de/DNSZone: #@ "{}".format(data.values.INFOBLOX_DNS_ZONE)
```
