### ISSUE TITLE
kube-apiserver does not restart after updating kube-apiserver.yaml file

### ISSUE THREAD

**Issue by balusarakesh** [aws/eks-anywhere#4590]
**What happened**:
 - updated `/etc/kubernetes/manifests/kube-apiserver.yaml` file with IRSA config but kube-apiserver does not restart
**What you expected to happen**:
 - kube-apiserver should restart

**How to reproduce it (as minimally and precisely as possible)**:
 - create an eks-anywhere cluster on an EC2 instance
 - follow this doc to setup an OIDC provider for pod IAM IRSA
 - add the kube-apiserver flags mentioned [here](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#kubernetes-api-server-configuration) to `/etc/kubernetes/manifests/kube-apiserver.yaml`

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-west-2
- EKS Platform version (1.21, using EKS-Anywhere)
- Kubernetes version (1.21)

cluster config:
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: test-cluster
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: test-cluster
  kubernetesVersion: "1.21"
  managementCluster:
    name: test-cluster
  workerNodeGroupConfigurations:
  - count: 3
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: test-cluster
spec: {}

```

command ran to create the cluster `eksctl anywhere create cluster -f test-cluster.yaml`

more context: basically I'm trying to enable IRSA on the pods so that they can assume IAM roles on my EKS-Anywhere cluster running on EC2 instance.
The document [here](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#kubernetes-api-server-configuration)  is not very clear, it says that I need to add those flags but doesn't say where exactly those flags need to be added.

I restarted `kubelet` and `containerd` and I still don't see `kube-apiserver` come up, it just get's killed when I update the `kube-apiserver.yaml`

I add the following config:
args:
```
 - --api-audiences="sts.amazonaws.com"
 - --service-account-key-file="/etc/kubernetes/sa-pkcs8.pub"
 - --service-account-signing-key-file="/etc/kubernetes/sa.priv"
 - --service-account-issuer="https://s3-us-west-2.amazonaws.com/$S3_BUCKET"
```

volumes:
```
    name: sa-pub
   - hostPath:
      path: /etc/kubernetes/sa-pkcs8.pub
      type: File
    name: sa-pkcs8-pub
   - hostPath:
      path: /etc/kubernetes/sa.priv
      type: File
    name: sa-priv
```
volumemounts:
```
    - mountPath: /etc/kubernetes/sa-pkcs8.pub
      name: sa-pkcs8-pub
    - mountPath: /etc/kubernetes/sa.priv
      name: sa-priv
```
files `sa.priv` and `sa-pkcs8.pub` are manually added to the control plane node (docker container)
