### ISSUE TITLE
Copy packages command pulls from dev ECR location

### ISSUE THREAD

**Issue by raykrueger** [aws/eks-anywhere#5004]
**What happened**:
Copy Packages command seems to be pulling from the packageDevDomain location. https://github.com/aws/eks-anywhere/blob/main/pkg/curatedpackages/reader.go#L28

```
Error: registry copy: GET https://857151390494.dkr.ecr.us-west-2.amazonaws.com/v2/adot/aws-observability/aws-otel-collector/manifests/sha256:c6c5db250d6590dcea15a1634254395c37bdb9d60f8d36720a9040a941e50677: credential required for basic auth
```

**What you expected to happen**:
I expect copy packages command to pull from the production location, 783794618700.dkr.ecr.us-east-1.amazonaws.com

**How to reproduce it (as minimally and precisely as possible)**:
Execute copy packages as documented

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.14.1
- EKS Distro Release:

**Comment by TerryHowe** [comment]
A dev EKS-A bundle will cause `copy packages` to pull from dev packages account. It uses the location of the package controller helm chart to determine where to pull, so the EKS-A bundle would contain something like:
```
    packageController:
      helmChart:
        description: Helm chart for eks-anywhere-packages
        imageDigest: sha256:602bc3dc4ea82ec60dc70c93d2f018565774af0ce32e6375a7906424bc634c4f
        name: eks-anywhere-packages
        uri: public.ecr.aws/l0g8r8j6/eks-anywhere-packages:0.0.0-65fb625c1b0133ea0910ac23d60f464d04216243
```
where the public ECR is l0g8r8j6
