### ISSUE TITLE
Baremetal: error occurs when tries to upgrade cluster with 'rollingUpgradeParams' field

### ISSUE THREAD

**Issue by or9327** [aws/eks-anywhere#5253]
**What happened**: error occurs when tries to upgrade baremetal cluster with 'rollingUpgradeParams' field

**What you expected to happen**: upgrade cluster with rollingUpgradeParams

**How to reproduce it (as minimally and precisely as possible)**:

1. case 1
- config of eksa-mgmt-cluster.yaml:
```yaml
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: "192.168.1.100"
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-bm-cp
    upgradeRolloutStrategy:
      rollingUpgradeParams:
        maxSurge: 0
        maxUnavailable: 1
```
- error:
Error: the cluster config file provided is invalid: unable to parse eksa-mgmt-cluster.yaml file: error unmarshaling JSON: while decoding JSON: json: unknown field "rollingUpgradeParams"

2. case 2
- config of eksa-mgmt-cluster.yaml:
```yaml
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: "192.168.1.100"
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-bm-cp
    upgradeRolloutStrategy:
       maxSurge: 0
       maxUnavailable: 1
```
- error:
Error: the cluster config file provided is invalid: unable to parse eksa-mgmt-cluster.yaml file: error unmarshaling JSON: while decoding JSON: json: unknown field "maxSurge"

3. case 3
- config of eksa-mgmt-cluster.yaml:
```yaml
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: "192.168.1.100"
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-bm-cp
  upgradeRolloutStrategy:
    rollingUpgradeParams:
      maxSurge: 0
      maxUnavailable: 1
```
- error:
Error: the cluster config file provided is invalid: unable to parse eksa-mgmt-cluster.yaml file: error unmarshaling JSON: while decoding JSON: json: unknown field "upgradeRolloutStrategy"

**Anything else we need to know?**: 
- reference : https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-upgrades/baremetal-upgrades/#advanced-configuration-for-rolling-upgrade

**Environment**: 
- EKS Anywhere Release:   v0.14.2
- EKS Distro Release: 1.24, 1.25

**Comment by jiayiwang7** [comment]
Doc updated. will be alive after the v0.15.0 release

**Comment by or9327** [comment]
Thanks for reply.

However, even though I changed the configuration file as you informed, still get config errors.

- case 4) Error: the cluster config file provided is invalid: unable to parse eksa-mgmt-cluster.yaml file: error unmarshaling JSON: while decoding JSON: json: unknown field "maxUnavailable"
```yaml
    upgradeRolloutStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
```

- case 5) Error: the cluster config file provided is invalid: unable to parse eksa-mgmt-cluster.yaml file: error unmarshaling JSON: while decoding JSON: json: unknown field "rollingUpgradeParams"
```yaml
    upgradeRolloutStrategy:
      type: RollingUpdate
      rollingUpgradeParams:
        maxSurge: 0
        maxUnavailable: 1
```

- case 6) Error: the cluster config file provided is invalid: validating upgrade rollout strategy configuration: WorkerNodeGroupConfiguration: maxSurge and maxUnavailable not specified or are 0. maxSurge and maxUnavailable cannot both be 0
```yaml
    upgradeRolloutStrategy:
      type: RollingUpdate
      rollingUpgradeParams:
        maxSurge: 0
```

- case 7) Error: the cluster config file provided is invalid: unable to parse eksa-mgmt-cluster.yaml file: error unmarshaling JSON: while decoding JSON: json: unknown field "maxUnavailable"

```yaml
    upgradeRolloutStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
```
