### ISSUE TITLE
API Endpoint IP:Port

### ISSUE THREAD

**Issue by jhcook** [aws/eks-anywhere#534]
**What would you like to be added**:

It appears the Docker provider uses random allocated ports to the API endpoint. This is not ideal for automation -- although it can be handled. Rather, it would be nice to specify a port in the Cluster spec.

I notice in the Cluster CRD the following. Perhaps `port` should be created alongside `host`, or is this functionality already available by other means?

```
              controlPlaneConfiguration:
                properties:
                  ...
                  endpoint:
                    description: Endpoint defines the host ip and port to use for
                      the control plane.
                    properties:
                      host:
                        description: Host defines the ip that you want to use to connect
                          to the control plane
                        type: string
                    required:
                    - host
                    type: object
```

**Why is this needed**:

This is needed for automatic provisioning of ephemeral Docker development environments.
