### ISSUE TITLE
Snow amiID and nonRootVolume are ignored in v0.15.0

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#5566]
With EKS-A v0.15.0, the amiID and nonRootVolume fields are not properly passed to generate the underlying CAPAS template. 

cluster config

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: SnowMachineConfig
metadata:
  name: chy-gpu
spec:
  ami:
    id: s.ami-093a4691552988fbb
  devices:
  - 192.168.1.10
  instanceType: sbe-g.xlarge
  nonRootVolume:
    - size: 50
      deviceName: /dev/sdd
  sshKeyName: default
  containersVolume:
    size: 100
  network:
    directNetworkInterfaces:
    - dhcp: true
      index: 1
      primary: true
  osFamily: bottlerocket
  physicalNetworkConnector: SFP_PLUS
```

awssnowmachinetemplate

```yaml
...
spec:
  template:
    spec:
      ami:
        id: ""
      cloudInit:
        insecureSkipSecretsManager: true
      containersVolume:
        size: 100
      devices:
      - 192.168.1.10
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      imageLookupBaseOS: bottlerocket
      instanceType: sbe-g.xlarge
      network:
        directNetworkInterfaces:
        - dhcp: true
          index: 1
          primary: true
      osFamily: bottlerocket
      physicalNetworkConnectorType: SFP_PLUS
      sshKeyName: default
```
