### ISSUE TITLE
Cluster Creation fails with gitops enabled

### ISSUE THREAD

**Issue by snowkiterdude** [aws/eks-anywhere#5713]
Steps to reproduce:

1) create a cluster without gitops enabled and make sure everything is operating fine(verify cluster manifest file).
2) follow the instructions to enable gitops on your new management cluster https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-flux/#getting-started-with-eks-anywhere-gitops-with-any-git-source

setup on the EKS-A management server
```
$ sudo su - my-eksa-user
my-eksa-user@my-server:~$ source .my-env-file # EKSA_VSPHERE_USERNAME, EKSA_VSPHERE_PASSWORD, EKSA_GIT_KNOWN_HOSTS env vars are set
my-eksa-user@my-server:~$ ssh-keygen -t ecdsa -C "$(hostname -a)@$(hostname -d)" -f ~/.ssh/gitlab
my-eksa-user@my-server:~$ eval "$(ssh-agent -s)" && ssh-add ~/.ssh/gitlab
my-eksa-user@my-server:~$ ssh-keyscan -t ecdsa gitlab.com > ~/.ssh/gitlab_know_hosts
my-eksa-user@my-server:~$ ssh-keyscan -t ecdsa gitlab.com >> ~/.ssh/known_hosts
```
add a new key to my user in gitlab
test that I can pull the repo with the new key

Edit the already tested cluster manifest:

```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster-name
spec:
... # collapsed cluster spec fields
# Below added for gitops support
  gitOpsRef:
    kind: FluxConfig
    name: my-cluster-name-gitops
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-cluster-name-gitops
spec:
  systemNamespace: flux-system
  clusterConfigPath: "gitops/site/clusters/my-cluster-name" # dir already created with README.md on the main branch
  branch: "main"
  git:
    repositoryUrl: ssh://git@gitlab.com/my-company/teams/my-team/our-repo.git
    sshKeyAlgorithm: ecdsa
```

Delete the current cluster so I can retry with the gitops config added.
Delete the local cluster directory that was auto-created with kubeconfigs from the last cluster creation

Create the management cluster:
```
my-eksa-user@my-server:~$ eksctl anywhere create cluster --force-cleanup -f my-cluster-name.yaml
Error: creating Git provider: open : no such file or directory
my-eksa-user@my-server:~$
```

Okay let's try again but with `clusterConfigPath: ""`... same error

Log file:
Has standard startup stuff creating tools container then nothing
/usr/bin/docker run -d --name ... --entrypoint sleep public.ecr.aws/eks-anywhere/cli-tools:v0.14.2-eks-a-28 infinity

```
my-eksa-user@my-server:~$ eksctl version
0.132.0
my-eksa-user@my-server:~$ eksctl anywhere version
v0.14.2
```

Any help would be appreciated!!!
