### ISSUE TITLE
CloudStackMachineConfig user details with empty values are not always propagated

### ISSUE THREAD

**Issue by chrisdoherty4** [aws/eks-anywhere#5791]
## Summary

The `CloudStackMachineConfig` offers a `userCustomDetails` field that are used to populate the CloudStack VM with 'settings' (arbitrary key-value pairs). When updating the `userCustomDetails` field with a new key-value or when changing the key-value it rolls out a new node. However, if the value is an empty string and the key name is changed, it doesn't recognize the new value, therefore doesn't roll out a new node.

**Example**

`create cluster` YAML:

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackMachineConfig
metadata:
  ...
spec:
  userCustomDetails:
    foo: ""
  ...
```

`upgrade cluster` YAML:

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackMachineConfig
metadata:
  ...
spec:
  userCustomDetails:
    bar: ""  // <- Change to the userCustomDetails key.
  ...
```

## What should happen?

Machines created from the `CloudStackMachineConfig` are recreated with the current `userCustomDetails`.

## Analysis

When checking if `userCustomDetails` has changed, [EKS-A checks the length and then iterates over all old values and checks if the new values are the same](https://github.com/aws/eks-anywhere/blob/a3e160645c4e0a9bff3350870131d3bb2fa9fbec/pkg/providers/cloudstack/cloudstack.go#L527-L538). In Go, a map lookup for a nonexistent key returns the zero value. Because the initial value, in the example above, was an empty string it fails to recognize `foo` has been removed.

## Other notes

[`symlinks`](https://github.com/aws/eks-anywhere/blob/a3e160645c4e0a9bff3350870131d3bb2fa9fbec/pkg/providers/cloudstack/cloudstack.go#L539-L550) may suffer from the same problem as the same algorithm is used to check key-value pairs.
