### ISSUE TITLE
Workload cluster creation via gitops fails with "err":"validating template tags..." using vsphere provider

### ISSUE THREAD

**Issue by snowkiterdude** [aws/eks-anywhere#5857]
**What happened**:
Create a management cluster with gitops enabled.
Add a workload cluster manifest to git repo.
watch the eksa-controller logs on the management cluster
```
{"ts":1683847189135.1758,"caller":"reconciler/reconciler.go:167","msg":"Invalid VSphereMachineConfig","controller":"cluster","controllerGroup":"anywhere.eks.amazonaws.com","controllerKind":"Cluster","Cluster":{"name":"my-workload-cluster","namespace":"default"},"namespace":"default","name":"my-workload-cluster","reconcileID":"7b292136-ce1d-4040-9f7a-1059968bff0b","provider":"vsphere","phase":"validateMachineConfigs","err":"validating template tags: govc returned error when listing tags for bottlerocket-v1.24.12-kubernetes-1-24-eks-15-amd64-00af48f: govc: 2 objects at path \"bottlerocket-v1.24.12-kubernetes-1-24-eks-15-amd64-00af48f\": [VirtualMachine:vm-9092 VirtualMachine:vm-9092]\n"}
```
or the same error if I try to use the Ubuntu templates we will actually be using.
```
{"ts":1683827795489.3894,"caller":"reconciler/reconciler.go:167","msg":"Invalid VSphereMachineConfig","controller":"cluster","controllerGroup":"anywhere.eks.amazonaws.com","controllerKind":"Cluster","Cluster":{"name":"my-workload-cluster","namespace":"default"},"namespace":"default","name":"my-workload-cluster","reconcileID":"279579b5-213b-49f2-a04b-fcda09e7348d","provider":"vsphere","phase":"validateMachineConfigs","err":"validating template tags: govc returned error when listing tags for ubuntu1-24: govc: 2 objects at path \"ubuntu1-24\": [VirtualMachine:vm-9067 VirtualMachine:vm-9067]\n"}
```
Note: the cluster manifests and templates have been validated by using the same manifest with the eksctl command. e.g. `eksctl anywhere create cluster -f my-workload-cluster.yaml --kubeconfig my-mgmt-cluster/my-mgmt-cluster-eks-a-cluster.kubeconfig`

The error appears to be getting generated from ./pkg/providers/vsphere/validator.go:220

tags setup:
```
eksusr@adm-vm:~$ govc tags.ls
os:ubuntu                           os
eksdRelease:kubernetes-1-24-eks-15  eksdRelease
os:bottlerocket                     os

eksusr@adm-vm:~$ govc tags.attached.ls eksdRelease:kubernetes-1-24-eks-15
VirtualMachine:vm-9067
VirtualMachine:vm-9092

eksusr@adm-vm:~$ govc tags.attached.ls eksdRelease:kubernetes-1-24-eks-15 | xargs govc ls -L
/my-dc/vm/Templates/ubuntu1-24
/my-dc/vm/Templates/bottlerocket-v1.24.12-kubernetes-1-24-eks-15-amd64-00af48f

eksusr@adm-vm:~$ govc tags.attached.ls os:ubuntu | xargs govc ls -L
/my-dc/vm/Templates/ubuntu1-24

eksusr@adm-vm:~$ govc tags.attached.ls os:bottlerocket | xargs govc ls -L
/my-dc/vm/Templates/bottlerocket-v1.24.12-kubernetes-1-24-eks-15-amd64-00af48f

```
Note I tried with just one template in vcenter with the same error so it is defiantly not that there are two VMs with the `eksdRelease:kubernetes-1-24-eks-15` tag(one ubuntu, one bottlerocket).

**What you expected to happen**:

Cluster creation success just like when we create the same cluster via `eksctl anywhere create cluster` command.

**How to reproduce it (as minimally and precisely as possible)**:

1) Create an ubuntu template via the procedure in the build artifacts page
2) Create a management cluster via eksctl with gitops enabled
3) create an ubuntu and bottlerocket workload cluster via the mgmt cluster with eksctl
Note: creating the bottlerocket workload cluster to auto-generate a bottlerocket template for us to validate that the Ubuntu template is not the issue(same issue with the provided template as our built template)
4) Create a bottlerocket workload cluster via gitops using the same manifest as we did with eksctl just change the cluster name in all the references.
5) same as step 4 but with the ubuntu template
We get the same error no matter what template we are using

Here is an example of the cluster manifest I'm using:
```
---
# cluster spec
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: my-workload-cluster
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: 10.10.10.2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: my-workload-cluster-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: my-workload-cluster
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: my-workload-cluster-etcd
  kubernetesVersion: "1.24"
  managementCluster:
    name: my-mgmt-cluster
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: my-workload-cluster
    name: md-0

---
# datacenter spec
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: my-workload-cluster
  namespace: default
spec:
  datacenter: my-dc
  insecure: false
  network: my-vlan
  server: my-vcenter.mydomain.local
  thumbprint: 01:02:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab

---
# control_nodes spec
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: my-workload-cluster-cp
  namespace: default
spec:
  datastore: my-datastore
  diskGiB: 25
  folder: my-workload-cluster
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  template: ubuntu1-24
  resourcePool: /my-dc/host/my-dc/Resources
  users:
    - name: ec2-user
      sshAuthorizedKeys:
        - ssh-rsa AAAA/my/pub/key/for/this/cluster/xyz= user@server

---
# worker_nodes spec
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: my-workload-cluster
  namespace: default
spec:
  datastore: my-datastore
  diskGiB: 25
  folder: my-workload-cluster
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  template: ubuntu1-24
  resourcePool: /my-dc/host/my-dc/Resources
  users:
    - name: ec2-user
      sshAuthorizedKeys:
        - ssh-rsa AAAA/my/pub/key/for/this/cluster/xyz= user@server

---
# etcd_nodes spec
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: my-workload-cluster-etcd
  namespace: default
spec:
  datastore: my-datastore
  diskGiB: 25
  folder: my-workload-cluster
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  template: ubuntu1-24
  resourcePool: /my-dc/host/my-dc/Resources
  users:
    - name: ec2-user
      sshAuthorizedKeys:
        - ssh-rsa AAAA/my/pub/key/for/this/cluster/xyz= user@server
```

The git repo setup:
```
cd path/to/gitops/dir; tree
├── REAME.md
└── my-mgmt-cluster
    ├── eksa-flux-system
    │   ├── gotk-components.yaml
    │   ├── gotk-patches.yaml
    │   ├── gotk-sync.yaml
    │   └── kustomization.yaml
    ├── my-mgmt-cluster
    │   └── eksa-system
    │       ├── eksa-cluster.yaml
    │       └── kustomization.yaml
    └── my-workload-cluster
        └── eksa-system
            └── eksa-cluster.yaml
```

**Anything else we need to know?**:

I was having the same issue with v0.14.2 on all the versions of templates(1-22, 1-23, 1-24, 1-25) so I completely destroyed everything and updated govc, eksctl, eksctl anywhere, image-builder, and vsphere to the latest versions.  I then recreated just one Ubuntu template to make sure the environment was as up-to-date and clean as possible to recreate the issue.

**Environment**:
vSphere Client version 8.0.1.00000
govc version: 0.30.4
eksctl version: 0.140.0
eksctl anywhere version: v0.15.3
image-builder: build-37-v0.1.2
Template: os:ubuntu eksdRelease:kubernetes-1-24-eks-16 However eks anywhere v0.15.3 calls for eksdRelease:kubernetes-1-24-eks-15 so I removed the -16 tag and created/attached the -15 tag.  I will eventually create another bug report for the fact that there is no way to specify the minor version used in eks anywhere or the image-builder to get them to align up.  I'm fetching the tag from the template with `/usr/local/bin/govc ls
        --json path/to/ubuntu1-24 | from_json | json_query('elements[].Object.Config.VAppConfig.Property[?Label==`EKS_DISTRO_VERSION`].DefaultValue')`

Any help would be very much appreciated.  I would really like to use gitops for this project. I have not confirmed yet but it would not surprise me if I would have the same issue creating workload clusters with Terraform. I will try that as soon as I get some more time.

Thanks!
