### ISSUE TITLE
Update GitOps logic to support Kustomize v5

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#5993]
Flux helm controller v0.34.0 starts to support Kustomize v5.0.3: https://github.com/fluxcd/helm-controller/blob/v0.34.1/CHANGELOG.md#0340

Kustomize v0.5 includes multiple breaking changes and deprecations: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0

One deprecation that can affect EKS-A GitOps:
> We are deprecating the following kustomization fields. These fields will never be removed from the kustomize.config.k8s.io/v1beta1 Kustomization API, but they will not be included in the kustomize.config.k8s.io/v1 Kustomization API. When Kustomization v1 is available, we will announce the deprecation of the v1beta1 version. There will be at least two releases between deprecation and removal of Kustomization v1beta1 support from the kustomize CLI, and removal itself will happen in a future major version bump.
> - patchesStrategicMerge. Please use [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/) instead

EKS-A pushes kustomization.yaml file to Git repo with format:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{.Namespace}}
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patchesStrategicMerge:
  - gotk-patches.yaml
```

We need to update the apiVersion to `kustomize.config.k8s.io/v1` and use `patches` instead of the deprecated `patchesStrategicMerge` once the v1beta1 api is deprecated.
