### ISSUE TITLE
vSphere cluster machine provisioning encountered Cilium error: Dead loop on virtual device cilium_geneve

### ISSUE THREAD

**Issue by ph-armada** [aws/eks-anywhere#6032]
**What happened**:
vSphere cluster machine provisioning encountered Cilium error: Dead loop on virtual device cilium_geneve

**What you expected to happen**:
Machine and cluster provisioning pass

**How to reproduce it (as minimally and precisely as possible)**:
Provision a vSphere cluster by following the EKS Anywhere instruction.
https://anywhere.eks.amazonaws.com/docs/getting-started/vsphere/vsphere-getstarted/

**Anything else we need to know?**:
How can we find logs related to this error? Please refer to the attached screenshot.
![image](https://github.com/aws/eks-anywhere/assets/134641967/41a12806-50e8-4cbf-8f09-c7468f994582)

**Environment**:
- EKS Anywhere Release: v0.16.0
- EKS Distro Release: N/A

**Comment by ph-armada** [comment]
Hi all - any suggestion on how to debug and mitigate this issue?

**Comment by jonathanmeier5** [comment]
@ph-armada can you share your cluster config?

**Comment by ph-armada** [comment]
Hi @jonathanmeier5 - I used the default setup as follows:
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt8
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "192.168.1.201"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt8-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: mgmt8
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt8-etcd
  kubernetesVersion: "1.27"
  managementCluster:
    name: mgmt8
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt8
    name: md-0
...
```
