### ISSUE TITLE
kindnetd cni config setup throws Error: applying kindnetd manifest for install: executing apply: error: no objects passed to apply

### ISSUE THREAD

**Issue by ph-armada** [aws/eks-anywhere#6097]
**What happened**:
kindnetd CNI setting throws error: applying kindnetd manifest for install: executing apply: error: no objects passed to apply

**What you expected to happen**:
deployment succeeded

**How to reproduce it (as minimally and precisely as possible)**:
1. Generate a cluster config: `eksctl anywhere generate clusterconfig $CLUSTER_NAME --provider vsphere > eksa-$CLUSTER_NAME-cluster.yaml`
2. Change the default `cilium` CNI to `kindnetd`: 
```
spec:
  clusterNetwork:
    cniConfig:
      kindnetd: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
 ```
3. Create cluster: `eksctl anywhere create cluster -f eksa-$CLUSTER_NAME-cluster.yaml -v 9  --force-cleanup `

**Anything else we need to know?**:
Logs:
```
2023-06-28T16:50:15.385Z	V3	Cleaning up long running container	{"name": "eksa_1687970707279414295"}
2023-06-28T16:50:15.385Z	V6	Executing command	{"cmd": "/usr/bin/docker rm -f -v eksa_1687970707279414295"}
Error: applying kindnetd manifest for install: executing apply: error: no objects passed to apply
```

**Environment**:
- EKS Anywhere Release: `v0.16.0`
- EKS Distro Release: N/A
