### ISSUE TITLE
EKSA on vSphere: Dead loop on virtual device cilium_geneve

### ISSUE THREAD

**Issue by soostdijck** [aws/eks-anywhere#6532]
**What happened**:

EKSA is happily provisioning most clusters (using the gitops method) on top of vmware vSphere, however my latest addition is giving me problems. Cilium is unhappy with the error:
> Dead loop on virtual device cilium_geneve, fix it urgently!

There is a similar issue #6032 which never seemed to have gotten to a solution.

**What you expected to happen**:

Cilium to work, just like all my other clusters.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster file for flux with something like this inside:
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: it-general-prod-eksa
  namespace: default
spec:
  managementCluster:
    name: mgmt-cluster
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
        - 10.213.8.0/21
    services:
      cidrBlocks:
        - 10.213.0.0/21
    nodes:
      cidrMaskSize: 24
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 10.213.0.10
    machineGroupRef:
      kind: VSphereMachineConfig
      name: it-general-prod-control-node
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: it-general-prod-vxrail-datacenter
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: it-general-prod-etcd-node
  kubernetesVersion: "1.27"
  workerNodeGroupConfigurations:
    - count: 4
      machineGroupRef:
        kind: VSphereMachineConfig
        name: it-general-prod-worker-node
      name: default-worker-node

# omitted some VSphereDatacenterConfig and VSphereMachineConfig
```

**Anything else we need to know?**:

**Environment**:
- vSphere
- EKS Anywhere Release: 0.16
- EKS Distro Release:

**Comment by csplinter** [comment]
Hi @soostdijck  - can you check to see if your `clusterNetwork.pods.cidrBlocks` range overlaps with your `VSphereDatacenterConfig.spec.network` range?

**Comment by soostdijck** [comment]
My `VSphereDatacenterConfig.spec.network` points to a "Distributed Port Group" inside vCenter, I'm not sure how that can overlap since that doesn't have a IP range as far as I know. All it has is a vlan ID inside vcenter. My dhcp server does give out the same range in that vlan as I have configured under `spec.clusternetworks.{pods,services}`

My VSphereDatacenterConfig looks like this:
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: it-general-prod-vxrail-datacenter
  namespace: default
spec:
  datacenter: "VxRail-Datacenter"
  insecure: true
  network: "/VxRail-Datacenter/network/EKSA_IT_GENERAL_PROD"
  server: "vcenter-1.redacted.net"
  disableCSI: false
```
