### ISSUE TITLE
OSImageURL is immutable

### ISSUE THREAD

**Issue by dborysenko** [aws/eks-anywhere#6834]
For baremetal, Is there a way to update OS Image for existing cluster?

Lets say I am running latest k8s 1.27 with latest eksa 0.17.4, I built an OS Image for that. 
Now I need to update an OS Image (lots of reasons, like upgrade third party package, maybe some intra company piece of software needs to be updated/replaced/added). Expected path was to build new OS Image, publish it on web server and refer within cluster-config.yaml as an updated spec.OSImageURL field. If you follow above procedure below error is shown:

```
eksctl anywhere upgrade cluster -f eksa-lab01.yaml --hardware-csv hardware.csv --no-timeouts
Performing setup and validations
✅ Tinkerbell provider validation
✅ Validate OS is compatible with registry mirror configuration
✅ Validate certificate for registry mirror
✅ Control plane ready
✅ Worker nodes ready
✅ Nodes ready
✅ Cluster CRDs ready
✅ Cluster object present on workload cluster
✅ Upgrade cluster kubernetes version increment
✅ Upgrade cluster worker node group kubernetes version increment
✅ Validate authentication for git provider
❌ Validation failed	{"validation": "validate immutable fields", "error": "spec.OSImageURL is immutable. Previous value http://eksatnpr-mssn01.example.com:8080/ubuntu.gz,   New value http://eksatnpr-mssn01.example.com:8080/v0-17-4/ubuntu.gz", "remediation": ""}
✅ Validate cluster's eksaVersion matches EKS-A Version
✅ Validate pod disruption budgets
✅ Validate eksaVersion skew is one minor version
Error: failed to upgrade cluster: validations failed
```

**Comment by pokearu** [comment]
Hi @dborysenko the support for changing the OSImageURL will be supported from our 0.18.0 release. Its currently disabled so this is the expected behavior.

**Comment by ph-armada** [comment]
Hi @dborysenko and @pokearu - may I know how do you handle the stream image link in the tinkerbell workflow template config? e.g.

```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellTemplateConfig
metadata:
  name: mgmt03-worker
  namespace: default
spec:
  template:
    global_timeout: 6000
    id: ""
    name: mgmt03-worker
    tasks:
    - actions:
      - environment:
          COMPRESSED: "true"
          DEST_DISK: /dev/sda
          IMG_URL: https://example.com/image.gz
        image: public.ecr.aws/eks-anywhere/tinkerbell/hub/image2disk:6c0f0d437bde2c836d90b000312c8b25fa1b65e1-eks-a-15
        name: stream-image-1
        timeout: 1200
```

If I changed them, the error says:
```
error when patching \"STDIN\": admission webhook \"validation.tinkerbellmachinetemplate.infrastructure.x-k8s.io\" denied the request: TinkerbellMachineTemplate.Spec is immutable\n", "retries": 288}
```
