### ISSUE TITLE
Allow to use hostname in TinkerbellTemplateConfig templating

### ISSUE THREAD

**Issue by Cajga** [aws/eks-anywhere#7538]
**What would you like to be added**:
We have the need to modify the default netplan config for Bare Metal, to be able to use bonding configuration with static IP assignment (we 2 bonds, one for storage one for data traffic). We generated the `TinkerbellTemplateConfig` with `eksctl anywhere generate tinkerbelltemplateconfig -f cluster.yaml` and noticed that some teampleting can be used for the actions:
```
DEST_DISK: '{{ index .Hardware.Disks 0 }}'
```

Our plan is to fetch the netplan files from the admin host using curl (through a cexec action). As we need a per host based netplan it would be nice to include the hostname in the URL through a tamplate like:
```
      - environment:
          BLOCK_DEVICE: '{{ formatPartition ( index .Hardware.Disks 0 ) 2 }}'
          CHROOT: "y"
          CMD_LINE: curl --output /etc/netplan/config.yaml http://adminhost.example.com:8080/netplan/{{ .Hardware.Hostname }}.yaml
          DEFAULT_INTERPRETER: /bin/sh -c
          FS_TYPE: ext4
        image: public.ecr.aws/eks-anywhere/tinkerbell/hub/cexec:6c0f0d437bde2c836d90b000312c8b25fa1b65e1-eks-a-15
        name: fetch-netplan-from-admin-host
        timeout: 90
```

But unfortunately, we could not find any documentation about this templating (`.Hardware.Disks`). However from the upstream code, it seems, only disks are added at the moment: https://github.com/tinkerbell/tink/blob/v0.10.0/internal/workflow/reconciler.go#L134

Is this the correct code? Would it be possible to extend this struct with more information like `hostname` so we can use it in TinkerbellTemplateConfig actions?

**Why is this needed**:
Currently we have very limited capabilities in TinkerbellTemplateConfig when it comes to a per host property (like an IP address of a bond interface). This forces us to define a TinkerbellTemplateConfig per host basically. If the templating could be extended with per host based variables (like hostname) then a single TinkerbellTemplateConfig could be used for many use cases.
