### ISSUE TITLE
[Bare Metal] Workload cluster scale out CLI validations fails with generated ssh keys

### ISSUE THREAD

**Issue by jacobweinstock** [aws/eks-anywhere#7991]
**What happened**:
I have a running workload cluster with 1 node in total. 1 control plane. When I create this cluster i did not define an SSH public key. As such, EKS Anywhere created one for me. When scaling up this workload cluster from 1 control plane node to 1 control plane by adding the following to the cluster yaml for the workload the `eksctl anywhere cluster upgrade` command fails.

The following was added to my successful 1 node cluster cluster.yaml:

```yaml
workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: workload-test-worker
    name: md-0
```

AND

```yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: workload-test-worker
spec:
  hardwareSelector:
    type: worker-wl
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
```

I get the following error:

```bash
V0	❌ Validation failed	{"validation": "SSH Keys present", "error": "[workload-test-cp TinkerbellMachineConfig is invalid: it should contain at least one SSH key, workload-test-worker TinkerbellMachineConfig is invalid: it should contain at least one SSH key]", "remediation": "Please include at least one SSH key per machine config. If your keys were autogenerated during the create cluster operation, make sure you include them in your cluster config for all lifecycle operations"}
.
.
.
V0	❌ Validation failed	{"validation": "validate immutable fields", "error": "spec.Users[0].SshAuthorizedKeys[0] is immutable. Previous value ssh-rsa ... ,   New value ssh-rsa ... ", "remediation": ""}
```

**What you expected to happen**:
Once an SSH public key has been provided to a cluster, either by the user or auto-generated by EKSA, the CLI should not require me to provide them. The cluster already has them/knows about them. Just use them.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: cli version v0.19.2
- EKS Distro Release:
