### ISSUE TITLE
GitOps setting with local git server is not working

### ISSUE THREAD

**Issue by ygao-armada** [aws/eks-anywhere#8542]
**What happened**:
I create a local git server, and I'm able to make a clone like `git clone git@<server>:/home/git/myproject.git`

However, when I use following GitOps setting in the cluster yaml file, and try to create a EKS anywhere cluster on bare metal, I see this error:
`Error: connecting with remote origin for repository: ssh: handshake failed: knownhosts: key is unknown`

```
spec:
  ...
  gitOpsRef:
    kind: FluxConfig
    name: my-git-flux-provider
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
 name: my-git-flux-provider
spec:
  git:
      repositoryUrl: "ssh://git@<server>//home/git/myproject.git"
      sshKeyAlgorithm: ecdsa
```

I try to replace the ~/.ssh/known_hosts_eksa content with the rsa public key of user git, and change the sshKeyAlgorithm to "rsa", it shows the same error.

**What you expected to happen**:
I'm able to create an EKSA cluster with GitOps setting on bare metal successfully.

**How to reproduce it (as minimally and precisely as possible)**:
I mention the steps above.

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.18.7
- EKS Distro Release: 1.28
