### ISSUE TITLE
EKS Anywhere Cluster Creation Fails on vSphere Datacenter with a Space in its Name 

### ISSUE THREAD

**Issue by minasys** [aws/eks-anywhere#908]
**What happened**:
Trying to create an eks-a cluster with the following VSphereMachineConfig 
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: eksa-temp-cluster-cp
spec:
  datastore: /example Lab/datastore/LabStorage
  diskGiB: 25
  folder: "EKS Anywhere"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: "ubuntu"
  resourcePool: /example Lab/host/Lab/Resources #/Murray Lab/host/Lab/Resources
  template: /example Lab/vm/EKS Anywhere/ubuntu-2004-kube-v1.21.2
```
and it succssfully validated the following stuff:
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
✅ Datastore validated
✅ Folder validated

but it fails validating the resource pool giving the following following error:

`❌ Validation failed    {"validation": "vsphere Provider setup is valid", "error": "error validating vCenter setup for VSphereMachineConfig eksa-temp-cluster-cp: resource pool '/example\\ Lab/host/Lab/Resources' not found", "remediation": ""}`

Then I tried escaping the space in the datacenter name,
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: eksa-temp-cluster-cp
spec:
  datastore: /example\ Lab/datastore/LabStorage
  diskGiB: 25
  folder: "EKS Anywhere"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: "ubuntu"
  resourcePool: /example\ Lab/host/Lab/Resources 
  template: /example\ Lab/vm/EKS Anywhere/ubuntu-2004-kube-v1.21.2
```
But it also fails giving the same error

```
Error: failed to create cluster: validations failed
❌ Validation failed    {"validation": "vsphere Provider setup is valid", "error": "error validating vCenter setup for VSphereMachineConfig eksa-temp-cluster-cp: resource pool '/example Lab/host/Lab/Resources' not found", "remediation": ""}
```

**What you expected to happen**:

Is to create the cluster with no issue
**How to reproduce it (as minimally and precisely as possible)**:
create the cluster on a datacenter with a space in its name.

**Anything else we need to know?**:
No

**Environment**:
- EKS Anywhere Release: v0.6.0
