### ISSUE TITLE
Hardware affinity support

### ISSUE THREAD

**Issue by SungHoHong2** [aws/eks-anywhere#9456]
**What would you like to be added**:
Does EKSA support for TinkerbellMachineTemplate featured in Cluster API? 

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellMachineTemplate
metadata:
  name: capi-quickstart-md-0
  namespace: capt-system
spec:
  template:
    spec:
      hardwareAffinity:
        required:  # 'required' entries are OR'd
        - labelSelector:
            matchLabels:
              manufacturer: dell
            matchExpressions:
            - key: idracVersion
              operator: In
              values: ["7", "8"]
        preferred: # 'preferred' entries are sorted by weight and then sequentially evaluated
        - weight: 50
          hardwareAffinityTerm:
            labelSelector:
              matchLabels:
                rack: 1
                room: 2
```

**Why is this needed**:
Currently, I have a issue of provisioning  control plane to servers in different racks.
I believe EKSA does not have a way to leverage the labels for control planes. 
It will be really useful to have.
