### ISSUE TITLE
Trouble Deploying Cluster Behind Proxy – CNI Not Initializing (Bare Metal)

### ISSUE THREAD

**Issue by max18557** [aws/eks-anywhere#9568]
## Summary  
Hi, I'm trying to deploy an EKS Anywhere test cluster behind a proxy, and running into issues with the control plane never becoming Ready. It seems to be related to the CNI not initializing properly. I'm not sure if I'm missing something in my setup or if there's a known issue with this configuration.

## ✅ Working Scenario

- When the subnet has **direct internet access**
- **No proxy defined**
- Cluster deploys and functions correctly

## ❌ Failing Scenario

- Proxy is defined (set up to allow my subnet access to all URLs in EKS-A documentation)
- VM boots into Rocky 9 image successfully
- CNI (Cilium) **does not initialize**
- Control plane nodes stay in **Not Ready** state
- Installer does not progress beyond this point

## 🧱 My Environment

- **eksctl version**: 0.205.0
- **kubectl version**: v1.32.2
- **eksctl anywhere version** : v0.22.0
- **Kubernetes version:** `1.31`
- **Node OS:** `Rocky Linux 9`  
  *(Used successfully without proxy)*
- **Admin machine:** `Ubuntu 22.04`
- **Infrastructure:** VMs (bare metal install flow – unsupported hypervisor)
- **Network:**  
  - `/24` subnet  
  - **No internet access**  
  - **No DHCP server**
- **Proxy:**
  - Allows access to all documented EKS-A URLs
  - Logs during cluster creation show only HTTP 200 responses

## 🔍 What I've Tried

- ✅ Bypassing the proxy → works
- 🔁 Testing various proxy and `no_proxy` configs
- ⚙️ Manually installing Cilium  
  - This causes master nodes to become Ready  
  - But installer doesn’t continue — still sees master as Not Ready
- 🧪 Misc tweaks and config changes

## 📄 Logs and config files

<details>
<summary>Expand </summary>

**console**:
2025-03-17T10:43:42.330Z        V5      Error happened during retry     {"error": "cluster condition ControlPlaneReady is False: Control plane nodes not ready yet, 1 expected (0 ready)", "retries": 3118}
2025-03-17T10:43:42.330Z        V5      Sleeping before next retry      {"time": "1s"}
2025-03-17T10:43:43.331Z        V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1742204336690132027 kubectl get --ignore-not-found -o json --kubeconfig mgmt/generated/mgmt.kind.kubecon
fig Cluster.v1alpha1.anywhere.eks.amazonaws.com --namespace default mgmt"}
2025-03-17T10:43:43.484Z        V5      Error happened during retry     {"error": "cluster condition ControlPlaneReady is False: Control plane nodes not ready yet, 1 expected (0 ready)", "retries": 3119}
2025-03-17T10:43:43.484Z        V5      Sleeping before next retry      {"time": "1s"}
2025-03-17T10:43:44.484Z        V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1742204336690132027 kubectl get --ignore-not-found -o json --kubeconfig mgmt/generated/mgmt.kind.kubecon
fig Cluster.v1alpha1.anywhere.eks.amazonaws.com --namespace default mgmt"}
2025-03-17T10:43:44.633Z        V5      Error happened during retry     {"error": "cluster condition ControlPlaneReady is False: Control plane nodes not ready yet, 1 expected (0 ready)", "retries": 3120}
2025-03-17T10:43:44.640Z        V5      Timeout reached. Returning error        {"retries": 3120, "duration": "59m59.190193319s", "error": "cluster condition ControlPlaneReady is False: Control plane nodes
not ready yet, 1 expected (0 ready)"}
2025-03-17T10:43:44.643Z        V4      Task finished   {"task_name": "workload-cluster-init", "duration": "1h0m28.239411261s"}
2025-03-17T10:43:44.643Z        V4      ----------------------------------

start of **cluster.yaml**:
```yaml 
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: "10.1.1.15"
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: mgmt-cp
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: mgmt
  kubernetesVersion: "1.31"
  managementCluster:
    name: mgmt
  workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: mgmt
    name: md-0
  proxyConfiguration:
     httpProxy: http://proxy.mydomain.com:3128
     httpsProxy: http://proxy.mydomain.com:3128
     noProxy:
       - 10.0.0.0/8
       - 192.168.0.0/16
       - localhost
       - 127.0.0.1
``` 

Kubelet logs on provisioned master node:
Mar 24 18:45:18 eksa-cp01 kubelet[828]: E0324 18:45:18.321974     828 kubelet.go:2902] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network pl>
Mar 24 18:45:23 eksa-cp01 kubelet[828]: E0324 18:45:23.324192     828 kubelet.go:2902] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network pl>
Mar 24 18:45:28 eksa-cp01 kubelet[828]: E0324 18:45:28.330793     828 kubelet.go:2902] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network pl>
Mar 24 18:45:31 eksa-cp01 kubelet[828]: I0324 18:45:31.439605     828 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="kube-system/cilium-operator-8699f75dbf-w5hlv" podStartSLOdurat>
Mar 24 18:45:33 eksa-cp01 kubelet[828]: E0324 18:45:33.334022     828 kubelet.go:2902] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network pl>
Mar 24 18:45:38 eksa-cp01 kubelet[828]: E0324 18:45:38.335143     828 kubelet.go:2902] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network pl>
Mar 24 18:45:43 eksa-cp01 kubelet[828]: E0324 18:45:43.336873     828 kubelet.go:2902] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network pl>
Mar 24 18:45:48 eksa-cp01 kubelet[828]: E0324 18:45:48.338732     828 kubelet.go:2902] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network pl>
Mar 24 18:45:49 eksa-cp01 kubelet[828]: I0324 18:45:49.487082     828 kubelet_resources.go:45] "Allocatable" allocatable={"cpu":"2","ephemeral-storage":"28203451960","hugepages-2Mi":"0","memory":"7735024Ki>
Mar 24 18:45:53 eksa-cp01 kubelet[828]: E0324 18:45:53.340549     828 kubelet.go:2902] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network pl>
Mar 24 18:45:59 eksa-cp01 kubelet[828]: I0324 18:45:59.791144     828 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="kube-system/cilium-ndktb" podStartSLOduration=18.700650884 pod>
Mar 24 18:46:01 eksa-cp01 kubelet[828]: I0324 18:46:01.779439     828 reconciler_common.go:245] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kuberne>
Mar 24 18:46:01 eksa-cp01 kubelet[828]: I0324 18:46:01.780092     828 reconciler_common.go:245] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-dzh9m\" (UniqueName: \>
Mar 24 18:46:01 eksa-cp01 kubelet[828]: I0324 18:46:01.880668     828 reconciler_common.go:245] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kuberne>
Mar 24 18:46:01 eksa-cp01 kubelet[828]: I0324 18:46:01.880858     828 reconciler_common.go:245] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-7fgwh\" (UniqueName: \>
Mar 24 18:46:04 eksa-cp01 kubelet[828]: I0324 18:46:04.545884     828 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="kube-system/coredns-5494dc5958-fx9sr" podStartSLOduration=7284>
Mar 24 18:46:04 eksa-cp01 kubelet[828]: I0324 18:46:04.566670     828 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="kube-system/coredns-5494dc5958-v7zkq" podStartSLOduration=7284>
Mar 24 19:44:05 eksa-cp01 kubelet[828]: E0324 19:44:05.117073     828 upgradeaware.go:441] Error proxying data from backend to client: writeto tcp 127.0.0.1:47066->127.0.0.1:33493: write tcp 10.1.1.10:1>
Mar 25 02:25:36 eksa-cp01 kubelet[828]: E0325 02:25:36.246810     828 upgradeaware.go:441] Error proxying data from backend to client: writeto tcp 127.0.0.1:33070->127.0.0.1:33493: write tcp 10.1.1.10:1>
Mar 25 05:40:56 eksa-cp01 kubelet[828]: E0325 05:40:56.225055     828 upgradeaware.go:441] Error proxying data from backend to client: writeto tcp 127.0.0.1:55178->127.0.0.1:33493: write tcp 10.1.1.10:
